### ISSUE TITLE
IBM5150 just writes zeros to cassette 

### ISSUE THREAD

**Issue by BigAlUK99** [mamedev/mame#4076] opened 2018-10-06 20:41 UTC
The IBM5150 emulator just writes zeros to the emulated cassette.  No idea what I might be doing wrong here, but I have to assume that the statement regarding the correct function of this device is false.  I can't corroborate whether it actually reads cassette data because I can't write any :)

The emulator looks as if it is going through its paces writing to the file, but if I rewind and play, nothing loads. Closing MAME and inspecting the file shows it is full of 00H bytes - so either something is VERY quiet (!) or something's not connecting up the dots...

**Comment by MooglyGuy** [comment] 2018-10-06 20:43
For those of us who aren't familiar with the IBM 5150, could I inconvenience you for a set of steps that will reproduce the issue?

**Comment by BigAlUK99** [comment] 2018-10-06 21:06
I ran the emulator, booting into Cassette BASIC C1.10 _(or running BASIC from PC DOS 1.0 - it doesn't matter, behaviour's the same)_.   Once in BASIC I write some code, any code, so I have something to save. 
I then invoked the File Manager menu in MAME and made MAME create a "blank tape".

I've tried the following in any and all orders, and there's no difference in behaviour:

Use the Tape Control menu in MAME to put the cassette into record. (Making sure it is rewound first).
Type the line:
  save"cas1:SomeName"
Watched it pretend to save.
Quit MAME and hex-reviewed the cassette file.
The file grew longer than when created, but was full of zero bytes (00hex).

**Comment by MooglyGuy** [comment] 2018-10-06 21:10
Thanks for the detailed info! As I said I'm not familiar with the driver, but I see no harm in trying to take a crack at it. I've also reopened the issue, as I suspect you may have inadvertently clicked the "Close and comment" button instead of the "Comment" button.

**Comment by BigAlUK99** [comment] 2018-10-06 21:15
Yep - I'm such a noob.

**Comment by MooglyGuy** [comment] 2018-10-06 21:29
How did you manage to get PC-DOS 1.0 to boot? When I run MAME using a default configuration and the following options, all I get is a blinking cursor in the upper-left corner of the screen:

mame64 ibm5150 -flop1 .\software\pcdos100.img

I also get the same behavior if I use the software list entry as so:

mame64 ibm5150 pcdos1

**Comment by MooglyGuy** [comment] 2018-10-06 21:35
Disregard my previous comment. It just takes a long time to boot (even for an XT).

**Comment by BigAlUK99** [comment] 2018-10-06 21:42
No kidding!
XT? - Why XT?
The IBM 5160 XT did not have a tape port.  
It is the IBM 5150 PC you should be using here.

**Comment by MooglyGuy** [comment] 2018-10-06 21:44
I meant "PC". I did say that I'm running the ibm5150 driver, after all. I'm trying to help here, so if you could dial the attitude back about twenty thousand notches, it would be much appreciated.

**Comment by BigAlUK99** [comment] 2018-10-06 21:44
Long time ago, I booted a real IBM 5150 into DOS.  I then went away and made a coffee and it had just delivered the A:> prompt when I returned.

**Comment by BigAlUK99** [comment] 2018-10-06 21:46
No attitude -  I was merely agreeing with you on the speed, and then I noticed you writing XT.  I'm aware that MAME emulates an XT as well, so I merely wanted to avoid you wasting time if you had genuinely made a mistake rather than a typo.

**Comment by MooglyGuy** [comment] 2018-10-06 21:50
Alrighty, no worries.

From a cursory examination of the driver, I don't see any calls to m_cassette->output at all, but I do see input and motor control hooked up, so that squares with the behaviour that you're seeing from the driver. Do you know offhand which PPI port cassette data is supposed to be written to, or should I grab the service manual?

**Comment by BigAlUK99** [comment] 2018-10-06 21:54
Like you, I'd have to find a manual.  Probably unlike you, I would not even be sure which manual to check first!  I've got loads of data downloaded, covering the full six-year lifespan of the 5150, so that would take me a while to find it.  I'll start now :)

**Comment by BigAlUK99** [comment] 2018-10-06 22:00
Found this (1981 Tech Ref).
Cassette User Interface
_The cassette interface control is implemented in software. (See FIRMWARE
Section). An 8253 timer output is used to control the data to the
cassette recorder. This output exits the System Board, at the rear,
through pin 5 of a DIN connector. The cassette input data is read by
an 8255A-5 Programmable Peripheral Interface (PPI) input port bit.
This signal is received through pin 4 of the cassette connector. Software
algorithms are used to generate and read cassette data. The cassette
drive motor is controlled through pins 1 & 3 ofthe cassette connector.
The motor on/off is controlled by an 8255A-PPI output port bit.
(Port '61H', bit 3). The 8255A address and bit assignments are defined
in the I/O Address Map page. On the following pages are read, write,
and motor control block diagrams._

**Comment by MooglyGuy** [comment] 2018-10-06 22:01
Brilliant, thanks! I think I have a fix, testing it now.

**Comment by BigAlUK99** [comment] 2018-10-06 22:02
:)

**Comment by MooglyGuy** [comment] 2018-10-06 22:05
:)! [0000](https://user-images.githubusercontent.com/1891617/46576195-a2637480-c9c4-11e8-86bc-5727cb29a04d.png)

**Comment by MooglyGuy** [comment] 2018-10-06 22:06
Before I check in, two questions:
1) Would you like to be credited in the changelog for this fix?
2) If so, what handle would you like me to use, if not BigAlUK99?

**Comment by BigAlUK99** [comment] 2018-10-06 22:10
Hey - I didn't fix it, you did.  :)

I'm just the irritating guy who likes testing things :)

But I'm fine with either BigAlUK (other forums) or BigAlUK99 (if the name's already been nicked, like on this forum), if you'd absolutely prefer to record my testing efforts.  No worries either way.

**Comment by MooglyGuy** [comment] 2018-10-06 22:14
Fix committed, cheers! The DIP switch issue seems a good bit more involved, though, so it'll have to wait until someone more familiar with the original IBM PC models rolls around to have a look.

**Comment by BigAlUK99** [comment] 2018-10-06 22:18
Ok - thanks for your sterling work.

**Comment by BigAlUK99** [comment] 2018-10-06 22:33
Am I supposed to close this now, or do you do that? 
And any idea how I get a copy of a fixed emulation?  Would it be released soon?
I'm not familiar with GitHub (as you've probably guessed).

**Comment by MooglyGuy** [comment] 2018-10-06 22:39
There are a couple of options in that regard.

One option is that you can grab the necessary toolchain to compile MAME at this link - https://www.mamedev.org/tools/ - and then simply click the green "Clone or Download" button here - https://github.com/mamedev/mame/ - and opt to "Download ZIP". Alternatively, you could install the same toolchain, as well as the Git source control software, clone the repo using the URL provided on the same button, and then compile it the same way. If you're only interested in the IBM PC driver, it's possible to compile a specific driver or drivers like so:

make SUBTARGET=pc SOURCES=src/mame/drivers/ibmpc.cpp

If you don't feel like faffing about with toolchains and big source downloads - and I wouldn't blame you if that's the case - then I'll be happy to spin up a standalone single-driver build for you and chuck it onto my webspace. Just let me know whether you're running a 64-bit OS or a 32-bit OS so I can compile the right version.

**Comment by BigAlUK99** [comment] 2018-10-06 22:42
That would be much appreciated :)
I'm actually using a 64-bit Windows 7 as host.
Would this result in something I just inject into the MAME folder structure?

**Comment by BigAlUK99** [comment] 2018-10-06 22:50
By the way, on the PCem forum I've got a thread (more of a blog, because no-one is posting any replies - haha) that deals with the memory issues.  It all started partly because of MAME and the fact I was looking at other emulators to get a historically accurate set of 5150 emulations together.  I want ultimately to crack that nut of having a PC emulator that correctly uses a 10MB HDD under DOS2.0.  But this is all side-track (a sign of my age).  My point is that I created a BASIC program that runs in 12K (and can thus run in cassette basic with only 16K RAM fitted) that displays the switches on the 5150 and conjectures upon the base unit part number and the approximate age, given the combination of switches, ROM dates and (in some cases) peripherals like the graphics adapter.  It has turned into something of a CPUz for the IBM5150 machine (only), but could be quite useful to other people who want to check the basic emulation of the 5150 memory is working.  I can drop a url here to the latest version (probably still buggy as yet, but mostly functional - works on MAME, PCE and PCem).

**Comment by MooglyGuy** [comment] 2018-10-06 23:03
Sure, I wouldn't mind taking a look!

Can do on 64-bit MAME, I run 64-bit Windows 7 on my machine here at home. I've ZIPped it up and chucked it up here: http://polygonal-moogle.com/mame/builds/mame64_ibmpc.zip

If you're running the latest release of MAME already, then I don't believe any of the external files have changed since the monthly release about a week and a half ago, so you should be able to simply unzip it into the same directory as everything else - I gave it a specific executable name so there shouldn't be any conflicts.

Once you've verified the fix on your end, to close the issue you can just click on the "Close" button beneath the comment box. Once again, cheers!

**Comment by BigAlUK99** [comment] 2018-10-06 23:36
Sorry - trying to do many things at once!  I have downloaded your file and will test it in a moment.  I was just creating a suitably configuration-controlled copy of my program (in plain text, and on a 160K IMG file, and also a PCE-compatible CAS file - I can't do a MAME cassette file yet, for obvious reasons.)

After that, I shall test your build. Thanks hugely.

I shall post a link to all the memory-sanity-checker under the Memory-related MAME issue, rather than here, since I will be closing this one out (I don't know what happens when I do that - does the earth explode?)

**Comment by MooglyGuy** [comment] 2018-10-07 00:13
No rush! It's the weekend, after all. :)

**Comment by BigAlUK99** [comment] 2018-10-07 00:39
Posted - but as it was so easy, I'll quickly post it here too   :)
[MotherBd.zip](https://github.com/mamedev/mame/files/2453519/MotherBd.zip)

**Comment by BigAlUK99** [comment] 2018-10-07 00:40
When you are retired, the whole week is one big long weekend :)

**Comment by MooglyGuy** [comment] 2018-10-07 01:28
Brilliant! I'm glad to have verification that it works on your end. I'll close the issue now, but in the event that you run into any additional cassette issues, feel free to open a new issue and I'll do my best to have a look. :)

**Closed by MooglyGuy** 2018-10-07 01:28 UTC
