### ISSUE TITLE
coco12.ccp, coco3.cpp, & dragon.cpp  related to keyboard mode (natural)

### ISSUE THREAD

**Issue by drencorxeen** [mamedev/mame#2386] opened 2017-06-15 05:47 UTC
If you are in Disk Basic OR OS-9/NitrOS-9 and try to use keyboard mode (natural) and use the SHIFT key it does not effect your typing at all.  So if you are in lower case mode and press SHIFT + R you do not get a upper case letter at all.  If I switch the keyboard mode back to (emulated) then the SHIFT key works fine.

So the (natural) keyboard mode needs to be fixed so you can use the SHIFT key.

Just tested the dragon.cpp in relation to this and it is also broken in there as well.  Can't use SHIFT while in Natural mode.

**Comment by drencorxeen** [comment] 2017-06-20 19:43
Ok so after further testing the SHIFT key seems to not work on A-Z keys when natural keyboard mode is on.

Also I noticed that when natural keyboard mode is on the Arrow Keys don't work.  I am using Shell+ and noticed that I wasn't able to bring up previously typed command line options.

**Comment by cuavas** [comment] 2017-06-21 01:02
I committed a fix for this.  Natural keyboard mapping should work better now, and emulated keyboard mapping should match the physical layout.  Please re-test CoCo 1/2/3 with the latest source.  I haven't done anything for Dragon.

**Comment by drencorxeen** [comment] 2017-06-21 07:02
@cuavas ,
I so far pulled and built the current sources.  I am currently testing coco3.  Here are my findings:
SHIFTED A-Z now work as expected.  Arrow keys partially work.  The SHIFTED Arrow keys do not work as expected.
Also noticed the Backspace does not work either.  Also noticed that in natural mode doing a SHIFT+- should give a underscore, but it doesn't.  On real CoCo keyboard this would be a CTRL+-

If I may ask, which file(s) contain the keyboard mappings for these?

**Comment by cuavas** [comment] 2017-06-21 09:17
Look at the commit to see where the keyboard mappings are.  The CoCo 3 does not have a backspace key, so it won't work in natural keyboard mode.  There's no real way to map shifted arrows in natural keyboard mode as they aren't characters as such.  You're probably better off just using emulated keyboard.  Natural keyboard is intended as a convenience feature when you're unfamiliar with the layout of the emulated system.

**Comment by drencorxeen** [comment] 2017-06-22 03:23
@cuavas , yeah I am starting to find out that trying to map natural to native is going to be really hard.

Yeah after looking at the coco3.cpp file I noticed the keyboard stuff in there.  The CoCo's backspace is technically the left arrow at the same time.

At least for now most of the keys are working.

**Closed** 2017-08-04 07:39 UTC

**Comment by mrgw454** [comment] 2017-08-13 21:57
npwoods referred me to this (closed) issue.  I am experiencing a LEFT arrow key/backspace issue starting with MAME-0.188.  I did not have this issue in the previous releases (at least the last 6 or so).  This includes the coco, coco2 & coco3 drivers (or variations thereof).  Should I open a new issue or can this one be reopened to investigate?  Thanks for any help you can provide.

**Comment by cuavas** [comment] 2017-08-14 00:35
What do you mean by "a LEFT arrow key/backspace issue"?  There is only one key that functions as both left arrow and backspace.  In emulated keyboard mode, this key is mapped to both left arrow and backspace by default.  In natural keyboard mode, it's mapped to left arrow only.  If this is the behaviour you're getting that is not a bug.

**Comment by mrgw454** [comment] 2017-08-14 00:47
In natural keyboard, the LEFT arrow will not move the cursor left unless I
hold down my CTRL key as well.  In emulated MODE, it moves left without any
issues.

Prior to MAME 0.188, the LEFT arrow would move the cursor left correctly in
MAME (Coco drivers) without any issue while in natural keyboard mode.  I
prefer the natural keyboard mode so this is why I wanted to mention the
difference I've noticed.

It may not be a bug, but something did change since the previous version.

Thanks for your quick response to my message

-Ron

**Comment by cuavas** [comment] 2017-08-14 00:56
OK, that's definitely odd, and I don't know what would be causing it.  Natural keyboard isn't supposed to be doing anything special with the control key on CoCo.  In fact, nothing is mapped to the control key at all in CoCo 1/2.  Does this affect other systems as well?  Without actually testing, it almost sounds like something screwy with arrow key handling in natural keyboard mode in general.

**Comment by mrgw454** [comment] 2017-08-14 01:06
I'll try to do more testing with some other MAME drivers.  I will say it
affects MAME's UI, so it has to be something outside of the individual
drivers.  Not sure if that helps.  I'm a huge fan of MAME (and the Coco) so
I use it quite a bit.  Thanks!
