### ISSUE TITLE
NBA Play By Play Problems

### ISSUE THREAD

**Issue by sjy96525** [mamedev/mame#2853] opened 2017-11-27 02:02 UTC
I play the NBA Play By Play has some Problems:
The Version has xxx:
https://i.imgur.com/ijnzz5A.png

NBA Play By Play 2D Graphics are not correctly in Start Button screen, see the Video:
https://i.imgur.com/5setWGb.png
https://www.youtube.com/watch?v=32ixZP4L6Jo
https://www.youtube.com/watch?v=1s5Sd7FCgP8
https://www.youtube.com/watch?v=QTg2VxM1DuE

Can you help?

**Comment by rb6502** [comment] 2017-11-27 04:11
Duplicate of 2796.  GX tile maps in non-GX games are broken until the Konami rewrite lands.

**Closed by rb6502** 2017-11-27 04:11 UTC
