### ISSUE TITLE
120hz Sync to monitor refresh make 2x game speed

### ISSUE THREAD

**Issue by iori3000** [mamedev/mame#557] opened 2016-01-06 18:45 UTC
0156 version 120hz with Vsync is 1x speed
nowday's versions are 2x speed
I want 120hz with Vsync is 1x speed

(edit by @balr0g: unfortunately the deletion of the intermediate comments removes all context from this issue)

**Comment by vgturtle127** [comment] 2016-02-08 17:30
@iori3000 Most games run at or less than 60Hz (as far as I know) so if you try to sync to your monitors faster refresh rate, it will go faster because the monitor refreshes at a faster rate than the game does.

This would be more of a problem if you select sync to monitor refresh rate, so if you uncheck that it should fix the problem. You won't run at 120Hz, but then again, MAME games tend to either not go that high in the FPS target anyway, or if they do they still aren't meant to be run at that refresh rate anyway.

I hope I was clear in my explanation.

**Comment by mr-t-guru** [comment] 2016-02-09 01:14
the 120Hz monitor refresh is purely something internal to the monitor/TV to create a more stable picture during fast action like sport. it has nothing to do with emulation, it's technology inside the monitor/TV and you can just ignore it. Personally I have found when I enable the 120Hz refresh on my 47" TV then watch some show the picture looks worse. IMO it's a gimmick to sell TVs. I leave the setting off. From an emulation point of view, as far as I'm aware, sync to refresh is a left-over from CRT screens and is no longer applicable to LCDs and current screen technology. the reality is no arcade game runs at 60Hz exactly. If you want the real speed just leave the refresh setting alone and the game will select the correct refresh rate based on the real PCB. If your monitor has problems keeping up get a better monitor. If you look around the net you can find people talking about this problem. I have found that Benq monitors have a wider range of refresh rates. For example my 22" Benq G922HDL is able to sync down to 15k and works with my Amiga 1200. So in reality it works like the old multi-sync monitors that had a very large range of HSync from 15k-38k. YMMV.

**Comment by u-man74** [comment] 2016-02-09 12:28
this is simply not true, what you are trying to say here. 120Hz refresh, is a invented Nvidia technology, that normally should insert blackframes, to reach way smoother motion, than the "normal" 60hz LCDs. Also these kind of monitors, are supporting variable sync refresh speeds, unlike the the usual LCD crap. It just seem, that it is currently not correctly supported with official MAME. I recommend iori3000 to try GroovyMame, as this derivative supports your monitor technology properly, because it have blackframe-insertion. You can find it here: http://forum.arcadecontrols.com/index.php/topic,135823.0.html

mr-t-guru: why the devs should remove sync-to-refresh? do you even know, how many users use a CRT in a Mame-cab? I am pretty sure, that they are many ;) . Please inform yourself better, before making such statements.

**Comment by mr-t-guru** [comment] 2016-02-09 13:28
I've used MAME on CRTs in arcade cabs and LCDs. I never had any problems with the base install.

**Comment by u-man74** [comment] 2016-02-09 13:58
then you are not using your CRT to full advantage... simple as that.

**Comment by mr-t-guru** [comment] 2016-02-09 14:09
eh? for me it works. I'm not having this conversation with you. you are on your own, I wont be replying again.

**Comment by u-man74** [comment] 2016-02-09 15:08
dude, of course it works... but it could work even better, if you know something about sync refresh, which seems you dont know.

**Comment by mamehaze** [comment] 2016-02-10 00:35
this isn't the best description, but is a valid topic of discussion, I say we leave it open.

a lot of current software will automatically insert black frames or similar if running at 120hz, which I think is what this is about because we don't do that.  It should be possible to run synced on a 120hz display with such a technique.

**Comment by vgturtle127** [comment] 2016-02-10 00:37
Did somebody delete my comment? Oh well.

@mamehaze Wouldn't that be horrendous? :laughing:

**Comment by mamehaze** [comment] 2016-02-10 00:38
actually it ends up improving clarity on a fair number of displays, I would expect horrible flicker myself, but the end result is actually strangely pleasing and reduces the motion blur issue a number of large screens have.

**Comment by mamehaze** [comment] 2016-02-10 00:40
and yes, unfortunately a rogue dev appears to have deleted your comments, that side of things will be dealt with internally, sorry about that.

**Comment by mamehaze** [comment] 2016-02-10 00:44
It is possible however that these screens ONLY handle 120hz properly, which would only apply to a tiny subset of the MAME titles, if they can't actually do 59.9 * 2 instead, or actually flicker badly at such a rate rather than giving the desired effect then it might turn out to not be feasible, but that will need to be discovered with time.

**Comment by rb6502** [comment] 2016-02-10 01:33
Haze: the screens in question are typically 120.0 only; they won't work well with the vast majority of MAME games.

Monitors compliant with GSync or FreeSync already work with stock MAME and -switchres and will sync exactly to oddball rates like 53 Hz or 59.97 or 60.1.

**Comment by balr0g** [comment] 2016-02-10 02:17
What's a bit confusing here is that the original poster seems to be indicating a potential regression? I'm not entirely certain......

**Comment by vgturtle127** [comment] 2016-02-10 07:26
@mamehaze Is there some sort of dynamic solution? Like a way to make it work with any refresh rate below 120Hz? I mean, technically there are 240Hz displays, but they are somewhat rare nowadays...

@rb6502 When you say 120.Hz only, you mean they will only run at 120Hz? I always thought most monitors supported multiple refresh rates (for example, I know of a monitor that is 120Hz that also supports 100Hz, 80Hz, 75Hz, 70Hz, and 60Hz.)

@balr0g Yeah, I was wondering about that too...

Another thing is that none of these games are meant to run at a refresh rate faster than the arcade cabinets monitors were normally set at (60Hz in the US, I guess? I actually never though about it or have done any research), and also the games should still run fine at the default refresh rate of the monitor, it doesn't cut down on the amount of frames if you run it at a different refresh rate on another monitor, it just means the game won't run as fast as your monitor can handle. Maybe I am missing something? Does anybody else get what I'm saying? :laughing: 

I feel like there is something wrong with the way this is working in my head. :laughing:

**Comment by galibert** [comment] 2016-02-10 09:32
You got it the wrong way around.  The game generates the sync signals at
whichever frequency it wants.  The monitor displays the result if the
frequencies happen to fall within its tolerances, otherwise it fucks up.
There is no feedback from the monitor to the game pcb whatsoever.  So the
game has its natural refresh rate, and is not designed to adapt to anything.

**Comment by u-man74** [comment] 2016-02-10 10:17
hahaha... deleted my posts... WTF? basically i have said all this already yesterday, but it seems that mr-t-guru is too sensitive :D .

**Comment by balr0g** [comment] 2016-02-10 17:51
@iori3000:
Can you repeat/reword the problem you have in detail? It seems like with all the churn it got lost here.

**Comment by rb6502** [comment] 2016-02-10 20:18
His specific claim is that -vsync -noswitchres on 0.156 with a 120 Hz video mode somehow the game ran normal speed.  To me that actually indicates that a bug was *fixed*, because the game running double speed with -vsync -noswitchres on a 120 Hz desktop is what I would expect to happen.

**Comment by vgturtle127** [comment] 2016-02-11 03:42
@rb6502 That's one of the things I was trying to say, I suppose. It may not necessarily be a regression so much as it actually working correctly.

@galibert OK, that makes more sense I suppose.

**Comment by iori3000** [comment] 2016-02-29 00:42
Sorry, it was some wrong and very poor discription and now I am so late for reading replys.

Vsync meant option of mameui
Properties - Advanced - [Sync to monitor refresh]
Not [Wait for vertical sync] option

I have actually 144hz benQ panel monitor, and I normally use it as 120hz setting
or sometimes I set it more exact double refresh hz of real acade machine for mame.
Because my monitor is not freesync or Gsync,
I use CRU util for exact double refresh setting, it is quite good.
For example, in neogeo 59.185606hz, I set monitor proximately 118.3712hz which is double of origin. 

Anyway, [Sync to monitor refresh] mame option make 2x boost run exceeding the normal speed.
This option didn't make 2x boost speed in old past version of mame with same monitor and setting.

I don't know whether this is potential regression or not,
but I can know that there was change by my testing old and new version.

I just wish it work properly with [Sync to monitor refresh] option in (static) around 120hz monitors.
I did like [Sync to monitor refresh] option because lower lag than Wait for vertical sync.

**Comment by MooglyGuy** [comment] 2016-02-29 01:48
@iori3000 I believe you misunderstand what these options do.

"Sync to monitor refresh" tells MAME to synchronize the refresh rate of the game in MAME to the refresh rate of your monitor.

Since you have set your monitor to 118.3712Hz, and you are telling MAME to match that refresh rate, then of course it will run at twice the speed.

In any case, I see you said the following:

"Vsync meant option of mameui"

I do not believe we accept bug reports for MAMEUI. If you can reproduce this behavior in command-line MAME as shipped on this github page, we will happily look into it. Otherwise, we may have to close this issue as it is not related to the official build of MAME.

**Comment by Robbbert** [comment] 2016-02-29 03:22
I've checked out what the 2 MAMEUI options do.

- Sync to Monitor Refresh --> syncrefresh
- Wait for Vertical Sync --> waitsync

When these options are adjusted, MAMEUI writes 0 or 1 to the option in the game's ini file. Then, when the game is started, the core reads the options and applies them in the expected way. However, as a matter of policy, bugs based on what happens in MAMEUI are not accepted.

You (iori3000) will need to verify that the same problem occurs with MAME downloaded from http://mamedev.org/release.html . If it cannot be reproduced, this issue will be closed.

Also, your report refers to "old past version of mame", but we need to know which version that is.

Thank you.

**Comment by iori3000** [comment] 2016-03-10 10:26
Sorry, I didn't know matter of policy.

Now, tried to test in mame0171b_64bit.exe
win7 64bit
gpu: hd4770 dx10.1
144hz monitor @120hz

Display Options Video Mode:
GDI and OpenGL has 100% speed no problem.
Auto and Direct3D has fixed 50% speed, no matter what the other options are.

**Comment by u-man74** [comment] 2016-03-10 14:22
From what i know and read about in the GroovyMAME forum regarding OpenGL, is that OpenGL dont accept the v-sync switch correctly from MAME. Instead you should use system/ATI control panel to achieve correct v-sync.
As previous posts already wrote, i suggest to use GroovyMAME, because it has black-frame insertion support and should handle the 120hz properly.
Your case can be also special, because you wrote: 
"I have actually 144hz benQ panel monitor, and I normally use it as 120hz setting or sometimes I set it more exact double refresh hz of real acade machine for mame.
Because my monitor is not freesync or Gsync, I use CRU util for exact double refresh setting, it is quite good."
So i assume that the handling is not the same, like with Gsync or freesync and maybe is the cause for your problems. Even Gsync or freesync is barely tested and i guess it gets worse with a benQ exclusive feature, as it is a far less common setup.

**Comment by vgturtle127** [comment] 2016-03-13 01:16
@iori3000 It seems there are several layers of potential issues here, but none of them seem to be caused by vanilla MAME, as far as I can tell.

Maybe sombody else can confirm or deny that, but I suspect there could be issues caused by the software you are using, MAMEUI, drivers, or maybe even the panel settings? I am by no means assuming I am correct in this, and is mostly wild speculation since I am not sitting right next to you, but I have a feeling some tweaking may alleviate your issue.

**Comment by Robbbert** [comment] 2017-12-26 11:00
Closing as requested by OP.

**Closed by Robbbert** 2017-12-26 11:00 UTC
