### ISSUE TITLE
mame can't remember last_used_filter

### ISSUE THREAD

**Issue by kokutoukiritsugu** [mamedev/mame#8634] opened 2021-09-30 03:46 UTC
mame0236b_64bit
windows 10.0.19043.1237(chinese language & non unicode program codepage aslo is chinese)

0 extract mame0236b_64bit.exe
1 open mame
2 select "Avaliable"
3 exit mame
4 ui.ini "last_used_filter" is "Available"
5 open mame, still select "Unfiltered"

==========

https://mametesters.org/view.php?id=7192
https://www.mameworld.info/ubbthreads/showflat.php?Cat=&Number=378966&page=&view=&sb=5&o=&vc=1
https://www.reddit.com/r/MAME/comments/egbmnk/can_i_pin_the_default_filter_when_running_mame/

maybe is local issue?

**Comment by kokutoukiritsugu** [comment] 2021-09-30 04:07
test in english(united states) language & no unicode program codepage is english (united states)

the last_used_filter works fine.

![image](https://user-images.githubusercontent.com/5471433/135385485-7e1b91fa-2d1a-4f66-8dce-1fc8e1d074d8.png)

**Comment by cuavas** [comment] 2021-09-30 09:00
My Windows 10 system is set to “English (United States)” as the display language, and “English (United States)” as the language for non-Unicode programs.  I cannot reproduce this issue.  Unfortunately, you’ll need to do some debugging to work out what’s actually going wrong.

**Comment by cuavas** [comment] 2021-09-30 09:00
Or are you saying it *doesn’t” work when the code page is changed?

**Comment by cuavas** [comment] 2021-09-30 20:40
I can reproduce it now, I’ll work out what’s going on.

**Comment by cuavas** [comment] 2021-09-30 21:13
Should be fixed as of 59e5f319c5300f9e5bd62a8da381348ed40a5310

**Comment by kokutoukiritsugu** [comment] 2021-10-01 14:14
download Artifacts https://github.com/mamedev/mame/actions/runs/1292720679 and replace mame.exe
on chinese non-unicode program codepage works fine.
👍👍👍

**Closed** 2021-10-01 14:14 UTC
