### ISSUE TITLE
Ultraman 1991 Banpresto 

### ISSUE THREAD

**Issue by Anths2016** [mamedev/mame#11087] opened 2023-04-09 18:18 UTC
### MAME version

0.253

### System information

Windows 10 64 bit

### Emulated system/software

Konami-Ultraman driver

### Incorrect behaviour

Only the shadows of the sprites are visible.

### Expected behaviour

Correct sprites views. 

### Steps to reproduce

Start the game and play.

**Comment by angelosa** [comment] 2023-04-09 18:40
This belongs to [MAMEtesters](https://mametesters.org/view.php?id=8602), ultraman shows like this in gameplay:
![0003](https://user-images.githubusercontent.com/9251271/230790583-13209afa-903c-4629-b030-1f7c2deec9c5.png)
Breakage happened between 0.246 and 0.248.
The issue is malformed, and can't be bothered to correct it, closing here, moving there.

**Closed by angelosa** 2023-04-09 18:40 UTC
