### ISSUE TITLE
RCA Studio II Emulation Broken

### ISSUE THREAD

**Issue by Sterophonick** [mamedev/mame#4633] opened 2019-02-12 21:24 UTC
Launching any RCA Studio II game leads to a corrupted screen.
No further information.

**Comment by Tafoid** [comment] 2019-02-12 22:54
Since this is a regression based on a released version, the best place for this bug report is at http://mametesters.org.   I'd encourage you to report there if you have any future verified bugs with any released binaries.  As far as this in concerned, all games start 'corrupted' but you need to hit **F3** then hold **Q** down until it boots.  In release versions prior to MAME 0.200, this should work.

Posted this to MT for you as I've done research to find when it broke and what (likely) broke it.
https://mametesters.org/view.php?id=7232

**Comment by Tafoid** [comment] 2019-02-14 22:17
This issue is to be handled by mametesters.org as it is logged and has comments.  Closing.

**Closed by Tafoid** 2019-02-14 22:17 UTC
