### ISSUE TITLE
Regression within zombraid in 0.250

### ISSUE THREAD

**Issue by sgpowers** [mamedev/mame#10626] opened 2022-12-02 01:26 UTC
Graphics corruptions as per image below, seems to be due to this commit: https://github.com/mamedev/mame/commit/7cbb49c5c77270898f58ed67238eb54014aa9a0d

`zombraid:`

![Screenshot from 2022-12-02 01-18-19](https://user-images.githubusercontent.com/28685555/205193380-1847f2bc-4cd7-482c-acc3-9cec09b7b64a.png)

**Comment by DavidHaywood** [comment] 2022-12-02 19:22
this kind of report really belongs on Mametesters rather than here.

Anyway, yes, it ends up doing partial updates.  I suspect the problem is the overall display timing is wrong
	screen.set_vblank_time(ATTOSECONDS_IN_USEC(0));
is completely unrealistic for example

**Comment by DavidHaywood** [comment] 2022-12-02 19:35
although changing that makes no difference, so it might be telling us something else

**Comment by sgpowers** [comment] 2022-12-02 23:59
Thanks @DavidHaywood 

I have created a Mametesters account, I'll transfer the issue there when I get permission to create a bug report.

**Comment by happppp** [comment] 2022-12-07 13:44
Closing because report was moved to https://mametesters.org/view.php?id=8530

**Closed by happppp** 2022-12-07 13:44 UTC
