### ISSUE TITLE
mame gamepad controller loses settings/configuration

### ISSUE THREAD

**Issue by tallpr24** [mamedev/mame#2387] opened 2017-06-15 12:23 UTC
Hey guys,
new to mame here.
I'm using mame0.816ui. My Xbox 360 controller wireless keeps losing the config in Mame.  I thought it was happening when I launched mame without my controller turned on but tried it again today and lost the config again even though the controller was on.  I changed the config file to be read only, not sure what else to do.  any suggestions.  I have mame and roms in the root of c drive.

**Comment by rb6502** [comment] 2017-06-15 12:47
0.816 or 0.186?  It makes a large (10 years) difference.

**Comment by tallpr24** [comment] 2017-06-15 13:56
lol, sorry I meant 0.186

----- Original Message -----

**Comment by happppp** [comment] 2017-06-15 18:47
duplicate of #1107
Please discuss there, I'll reopen the issue

**Closed by happppp** 2017-06-15 18:47 UTC
