### ISSUE TITLE
build problems related to python scripts

### ISSUE THREAD

**Issue by drencorxeen** [mamedev/mame#5649] opened 2019-09-16 19:10 UTC
I am getting these errors when building:
`
Traceback (most recent call last):
  File "d:/EMU/SRC/mame/scripts/build/makedep.py", line 211, in <module>
    parse_file(root,filename,'')
  File "d:/EMU/SRC/mame/scripts/build/makedep.py", line 162, in parse_file
    parse_file(root, fullname, newfolder)
  File "d:/EMU/SRC/mame/scripts/build/makedep.py", line 162, in parse_file
    parse_file(root, fullname, newfolder)
  File "d:/EMU/SRC/mame/scripts/build/makedep.py", line 166, in parse_file
    parse_file(root, fullname.replace('.h','.cpp'), newfolder)
  File "d:/EMU/SRC/mame/scripts/build/makedep.py", line 120, in parse_file
    for line in fp.readlines():
  File "C:/msys64/mingw64/lib/python3.7\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 488: character maps to <undefined>
Traceback (most recent call last):
  File "d:/EMU/SRC/mame/scripts/build/makedep.py", line 211, in <module>
    parse_file(root,filename,'')
  File "d:/EMU/SRC/mame/scripts/build/makedep.py", line 162, in parse_file
    parse_file(root, fullname, newfolder)
  File "d:/EMU/SRC/mame/scripts/build/makedep.py", line 162, in parse_file
    parse_file(root, fullname, newfolder)
  File "d:/EMU/SRC/mame/scripts/build/makedep.py", line 166, in parse_file
    parse_file(root, fullname.replace('.h','.cpp'), newfolder)
  File "d:/EMU/SRC/mame/scripts/build/makedep.py", line 120, in parse_file
    for line in fp.readlines():
  File "C:/msys64/mingw64/lib/python3.7\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 488: character maps to <undefined>
d:/EMU/SRC/mame/scripts/genie.lua:1554: attempt to call a nil value
stack traceback:
        d:/EMU/SRC/mame/scripts/genie.lua:1554: in main chunk
        [C]: in upvalue 'builtin_dofile'
        [string "premake = { }..."]:84: in function 'dofile'
        [string "_WORKING_DIR        = os.getcwd()..."]:45: in function '_premake_main'
make: *** [makefile:1053: build/projects/windows/mame/gmake-mingw64-gcc/Makefile] Error 1

`
Is there a easy way to fix this or workaround?

**Comment by happppp** [comment] 2019-09-17 09:09
Duplicate of https://github.com/mamedev/mame/issues/5482 ?
There's a workaround posted, try it.

**Closed** 2019-09-19 09:06 UTC
