### ISSUE TITLE
I cannot run mame on iphone

### ISSUE THREAD

**Issue by liuhua820522** [mamedev/mame#3031] opened 2018-01-08 14:50 UTC
Dear sir,
         Per title, thanks.

**Comment by happppp** [comment] 2018-01-08 15:20
duplicate of https://github.com/mamedev/mame/issues/3026
This is not an issue or bug with MAME code. Go to a web forum or reddit or IRC for user questions.

**Closed by happppp** 2018-01-08 15:20 UTC

**Comment by liuhua820522** [comment] 2018-01-08 15:34
Dear sir,
         I cannot post question on forum. I registered account but still not be approved. So if you can answer my question. Thanks.

**Comment by happppp** [comment] 2018-01-08 15:55
I suggest a local language forum, a Chinese forum? Personally I don't know any.
For English language:

Official forum: http://forum.mamedev.org/viewforum.php?f=14
forum on bannister.org(need approval): http://forums.bannister.org//ubbthreads.php?ubb=postlist&Board=1&page=1
MAMEWorld: http://www.mameworld.info/ubbthreads/postlist.php?Cat=&Board=mamechat

reddit: https://www.reddit.com/r/MAME/

official chat, with web IRC, for example:  https://kiwiirc.com/client/irc.freenode.net
channel is #mame
