### ISSUE TITLE
mame crashes with hidnctch

### ISSUE THREAD

**Issue by stargoonman** [mamedev/mame#2988] opened 2017-12-30 02:24 UTC
When you press button 1 after the round starts, it crashes.

Happens with the build from the latest commit

**Comment by stargoonman** [comment] 2017-12-30 03:04
outputs:

"Unimplemented: generate_subs (40008218)
Fatal error:"

**Comment by katananja** [comment] 2017-12-30 11:11
Can't reproduce.
Copile with:
`DEBUG=1 SYMBOLS=1 SYMLEVEL=1 STRIP_SYMBOLS=1`

And use -verbose and -log from command prompt.

**Comment by MooglyGuy** [comment] 2017-12-30 12:05
Confirmed, working on a fix.

**Comment by MooglyGuy** [comment] 2017-12-30 12:29
@stargoonman the issue should now be fixed with the latest code in the repository. Please do let me know if you run into any other fatalerrors in Hyperstone-based games.

**Comment by stargoonman** [comment] 2017-12-30 15:37
Tested for 30 mins and it seems to be working fine now!

**Comment by MooglyGuy** [comment] 2017-12-30 16:53
Excellent, thanks!

**Closed by MooglyGuy** 2017-12-30 16:53 UTC
