### ISSUE TITLE
UI font not readable in native resolution on crt

### ISSUE THREAD

**Issue by ArcadeTV** [mamedev/mame#7105] opened 2020-08-20 08:40 UTC
I've been pulling my hair about this for some time now.Any setting for the ui font I've tried doesn't improve readability on crt.

Tried any possible combination of **-uifont** and **-uifontprovider**.
Leaving **-uifont** blank or using **uismall.bdf**, the output is still too small and blurred.

I even installed fontforge and changed the base size of some common fonts like Arial, but though the font is displayed bigger, the spacing is anything but optimal with this workaround.

I know that the UI looked crisp in older Versions.

**Comment by cuavas** [comment] 2020-08-20 08:48
I just tested it on Windows and Linux using `-uifont uismall.bdf -window -resolution 320x240` with various `-video` modes, and it appears this issue is Windows-specifc.  @Tafoid would you be able to pin down a regression version for when it started displaying lots of tiny lines of text in the UI at small sizes and giving “scratchy” rather than “soft” scaling for low-resolution bitmap fonts?

**Comment by Robbbert** [comment] 2020-08-20 09:15
If it helps...
Tried on my 1680x1050 at 100%, win10: (number of lines is the number of games in the middle pane), with uismall.bdf, and default video mode
160x120 = 12 lines of unreadable text
320x240 = 12 lines of slightly larger (but still mostly unreadable) text
640x480 = 4 lines of large text
1280x960 = 23 lines of readable text
With no options (-window implied) I get 12 lines of large text with the window at about the 1280x960 size.

**Comment by cuavas** [comment] 2020-08-20 09:20
OK, I’m an idiot.  I mistyped the command on Windows.  Here’s what I get on Linux, results are similar on Windows if I type the command properly:
![Screenshot_20200820_191542](https://user-images.githubusercontent.com/9678431/90751895-0a51a880-e31a-11ea-8923-81ecacca0716.png)

**Comment by cuavas** [comment] 2020-08-20 09:21
Given it seems to be working, I’d guess it must be some kind of environmental issue.  Is your working directory set correctly so MAME can find the BDF file?

**Comment by MooglyGuy** [comment] 2020-08-20 10:16
What part of the text in the left-hand filter pane says "readable" to you?

**Comment by cuavas** [comment] 2020-08-20 10:25
Oh, the left pane has never worked properly at small sizes, and IIRC it lacks the ability to scroll.  However @ArcadeTV says, “I know that the UI looked crisp in older Versions,” so I was looking for a regression, not something that never worked in the first place (well, “never” being since we incorporated MEWUI).

**Comment by ArcadeTV** [comment] 2020-08-20 11:04
Thank you for looking into this!
I actually didn't test the "cabinet" menu, just the open-on-tab-key UI, including the "loading" message.
The system uses any font I define, either system-installed ttf or bdf in defined font-path, they are just rendered so small that when anti-alias kicks in, all text is blurred.
I may be mistaken about different bahaviour in previous versions, as it could be I used linux back then.
The UI-window that overlays the screen when I hit tab also seems to be pretty small, I will attach some images later.
Thanks again!

**Comment by ArcadeTV** [comment] 2020-08-20 15:11
![2020-08-20 17_06_14-Window](https://user-images.githubusercontent.com/26868804/90790128-0452cc00-e308-11ea-8e80-3fb6f0e84108.png)

In windowed-mode on another machine the text is pretty crisp.

**Comment by substring** [comment] 2020-09-15 11:12
Had the same issue in Linux. The best was to use a TTF font and play on ui.ini for a slightly bigger font. The only drawback : some boxes are too small for the text and can't be scrolled.

**Comment by cuavas** [comment] 2023-01-04 05:33
This fixed by fcee73320b0ddf778202eed51b06330f5c98f9f3.

`mame -uifont uismall.bdf`
![image](https://user-images.githubusercontent.com/9678431/210490597-83bc9aed-6765-4fab-841c-5f27455732ec.png)

**Closed by cuavas** 2023-01-04 05:33 UTC
Labels: bug, ui/ux
