### ISSUE TITLE
feature request: save settings

### ISSUE THREAD

**Issue by arcade-legend** [mamedev/mame#8321] opened 2021-07-20 20:08 UTC
Hi

All settings you can do by using the UI menu (TAB) are gone when restarting MAME.
It would be very usefull if we could save them by game and MAME loads the settings file for that game when restarted (RetroArch for example can save settings by game).
The way it works now, we need to redo ALL settings for each game over and over again...

**Comment by arcade-legend** [comment] 2021-07-20 20:09
This can also save you a lot of work when debugging.
The settings that cause problems can be saved and tested just by restarting MAME.

**Comment by cuavas** [comment] 2021-07-20 20:13
That isn’t true.  Input settings (host input bindings, analog sensitivity, DIP switch state, machine configuration state, and toggle and adjuster state) are saved per system in CFG files.  View settings are also saved per system in CFG files.  UI settings (e.g. menu colours, UI language, system selection menu options, etc.) are saved to ui.ini if you choose to save settings.  There are a few video options that can be set from the internal UI but can only be configured persistently by manually editing INI files.  Unless you can give specifics, this seems to be an invalid report.

**Comment by arcade-legend** [comment] 2021-07-20 20:24
I just give a random example (but many more exist). Go to "slider controls" and adjust "master volume".
Restart MAME and the setting you had chosen for the specific game is gone.
I don't see any option to save settings. Where can I find it?

**Comment by arcade-legend** [comment] 2021-07-20 20:27
Another example for video options:
"Video options" -> "Screen #0" -> "Maintain aspect ratio": after choosing on/off and restarting MAME, the setting is reset to "on".
For video options there is no save option either.

So what are you talking about?
Please give me an example of a setting that is saved and HOW to save it.

Thank you

**Comment by cuavas** [comment] 2021-07-20 20:30
The sound balance and overclock/underclock sliders are not saved by design.  Saving them across runs lead to an excessive number of false bug reports when people forgot they’d adjusted a slider and complained that things didn’t work properly.

Some sliders *are* saved though, notably the video adjustment ones that mimic CRT controls (brightness, contrast, gamma, position and size) are saved per system in CFG files.

“Maintain aspect ratio” is one of the few video options that can be set from the internal UI but can only be configured persistently by manually editing INI files, as already mentioned.

Closing as invalid report.  You can ask why things are the way they are on another forum.

**Closed by cuavas** 2021-07-20 20:30 UTC

**Comment by arcade-legend** [comment] 2021-07-20 23:38
Saving other sliders can generate bug reports too
you save ALL or nothing...
please stop telling fairy tales here!
