### ISSUE TITLE
nbashowtime issue with vegas midway drivers

### ISSUE THREAD

**Issue by patrikpatrik** [mamedev/mame#4620] opened 2019-02-08 17:43 UTC
I've been trying to figure this out for couple weeks now and it's a head scratcher. Other midway vegas titles such as gauntlet and blitz are playable. However, nba showtime freezes when it starts rendering 3d about 5-6 seconds. I've been examining these files for possible clues but everytime I seem to come back to vegas.cpp:

vegas.cpp
midwayic.cpp
voodoo_pci.cpp
voodoo_pci.h
vrc5074.cpp
mips3.h
mips3.cpp
vrc5074.h
drcfe.cpp
drcuml.cpp

Thanks to Ted Green for the amazing voodoo emulation work, not sure how in the world he manage to pull that off hats off to him! I've sent him an email regarding this issue and was told that it could be from the MIPS3 cpu not handling floating points properly. I've tried changing values on all of these just to see if I could delay or shorten that freeze time to at least establish a good location to troubleshoot but still freezes exactly 5-6 seconds in. Someone else had mentioned that it could be an IDE chip problem but I couldn't find anything substantial for this to be the case.

Ted did mention of something called an 'Inter vsync timeout' error which I haven't been able to spot. I've tried setting  PRINTF_SERIAL to 1 along with  ENABLE_02_DPRINTF to 1 in mips3.h but I don't see any output besides from the watchdog_reset warning a couple minutes after the freeze. Apparently cpu ends up in an infinite loop and that causes the hang to occur.

The only 'vsync timeout' error I could dig was from an obscure manual where certain ROMs would need some kind of pulse correction or else the game wouldn't run. I suppose this would sort of explain why the other games are playable and nba isn't. If it were a FPU cpu issue then the others wouldn't be working as well , or at least freezing to match the issue, but that's not the case either...

**Comment by MooglyGuy** [comment] 2019-02-08 17:57
The game is marked as "not working" in the driver for the reasons you describe. If you wish to submit a fix for the driver, feel free, but issue reports will not be accepted because the issue is already known.

Furthermore, ENABLE_O2_DPRINTF is specifically for the SGI O2 driver. Based on the fact that you are randomly enabling #defines without comprehending what they do, I am highly doubtful that you have the knowledge necessary to fix the issue in question.

**Closed by MooglyGuy** 2019-02-08 17:57 UTC
