### ISSUE TITLE
Street Fighter 2 Cammy Stage graphic bug

### ISSUE THREAD

**Issue by elessar38** [mamedev/mame#10259] opened 2022-08-23 11:05 UTC
Cammy Stage has a graphical bug. It's about strange flickering lines just below the aurora borealis.
The issue appears in: Hyper Streef Fighter 2, and SF2 Turbo.
Interestingly, SF2 New Challengers does not have this bug as the game is much slower than Hyper Street Fighter 2 and Turbo. In SF2 Turbo you can also use cheats to reduce the speed of the game: no frame skip, like SF2 " (which also fixes the graphics problem).

Scrennshot:
[https://zapodaj.net/77641d4bc1b53.png.html](url)

**Comment by angelosa** [comment] 2022-08-23 18:20
Duplicate of https://mametesters.org/view.php?id=8403
Also that link is very suspicious, removed.

**Closed by angelosa** 2022-08-23 18:20 UTC

**Comment by elessar38** [comment] 2022-08-23 21:48
It's hard for me to know that someone has already written about it since there are hundreds of problems reported. Should I read them all?
I'm a new github user and I don't know how to paste pictures. I added a screenshot where it was easiest for me.
The link was ok, it was enough to copy it to a new window.
BTW I got tired as hell to catch the glitch in the screenshot so thanks for nothing!

**Comment by angelosa** [comment] 2022-08-24 10:59
Cammy stage background breaking is a raster effect issue, which should be down to well acknowledged CPS-1 / CPS-2 timing issues.
Also again: player side bug reporting definitely go to https://mametesters.org regardless rather than GH issues (especially because we don't have templates here).

**Comment by cuavas** [comment] 2022-08-24 12:28
> It's hard for me to know that someone has already written about it since there are hundreds of problems reported. Should I read them all?

You should at least search for open bugs against the driver you’re testing to ensure you aren’t creating a duplicate.

You can attach files to GitHub issues by dragging them to the drop target below the text entry field, where it helpfully says “Attach files by dragging & dropping, selecting, or pasting them.”  You can also click it to open a file selection dialog, or paste an image from the clipboard.

**Comment by elessar38** [comment] 2022-08-24 14:59
Most importantly, the problem is known.
I hope it will be solved someday.
