### ISSUE TITLE
Added SFG-01/SFG-05(Yamaha UCN-01) extension support for usual MSX

### ISSUE THREAD

**Issue by denjhang** [mamedev/mame#10889] opened 2023-02-11 01:42 UTC
#8708
In fact, I reported similar content early, but I expressed it improperly. So I make another request: adapt YAMAHA SFG series modules.This must be a useful feature.Currently only the CX5M supports this extension, but virtually all MSXs can use an adapter to connect to the SFG.

**Comment by denjhang** [comment] 2023-02-11 01:44
@Tafoid What do you think of this??

**Comment by cuavas** [comment] 2023-02-11 18:00
It’s pointless opening issues for things you want emulated if you can’t actually contribute towards emulating them.  I’m going to have to ask you to refrain from doing this.

**Comment by angelosa** [comment] 2023-02-11 18:07
It's also a duplicate of the linked issue, gonna edit that one ...

**Closed by angelosa** 2023-02-11 18:07 UTC

**Comment by denjhang** [comment] 2023-02-12 00:39
> It’s pointless opening issues for things you want emulated if you can’t actually contribute towards emulating them. I’m going to have to ask you to refrain from doing this.

I admit this question is a duplicate. Do you think it's unreasonable to make a feature request? If yes, then please block all feature requests.
