### ISSUE TITLE
hsi files

### ISSUE THREAD

**Issue by the-namelessone** [mamedev/mame#7632] opened 2021-01-03 16:42 UTC
Hi

Since no forum, docs or anything can give an answer to this, I'm forced to ask here while it's not a mame issue.
But since there is no docs about this, it's indirectly a mame issue too...
Undocumented things are issues.

Why are there 5 hsi files in mame hash folder and what are they used for?
The files are a5200.hsi, intv.hsi, msx.hsi, msx2.hsi and nes.hsi

best regards

**Comment by happppp** [comment] 2021-01-03 16:50
duplicate of https://github.com/mamedev/mame/issues/7631

**Comment by the-namelessone** [comment] 2021-01-03 16:51
Point me to any docs about this please.
OR REMOVE THE UNDOCUMENTED FILES...

don't confuse people with this

**Closed by happppp** 2021-01-03 16:50 UTC
