### ISSUE TITLE
No Intel 440BX (82443BX) support.

### ISSUE THREAD

**Issue by Hydreigon223** [mamedev/mame#10534] opened 2022-11-10 23:44 UTC
savquest.cpp and midqslvr.cpp need proper 82443BX northbridge support. Registers between 82439TX and 82443BX are mapped differently and on an actual PC system, putting a Pentium I inside a 82443BX based motherboard won't properly boot and vice versa. It hasn't been acknowledged in the driver TODO list for both either.

82443BX datasheet: https://datasheet.octopart.com/FW82443BX-Intel-datasheet-5334749.pdf

**Comment by angelosa** [comment] 2022-11-10 23:54
Duplicate of #391 , unneeded, known, closing.

**Closed by angelosa** 2022-11-10 23:54 UTC
