### ISSUE TITLE
CEC(China Education Computer) Chinese input isn't work

### ISSUE THREAD

**Issue by DickyQi** [mamedev/mame#9838] opened 2022-05-27 16:04 UTC
CECx(AppleIIe China clone) device in Chinese input mode(PINYIN) isn't working since rev 3176606b601 (2022/1/19). rev 57faae18d8e (2021/12/11) is working fine.

**Comment by cuavas** [comment] 2022-05-27 16:12
The trouble is, the two commits you’ve given are on a defunct branch from a pull request.  The master revision branch merged into the feature branch at that point was cd51627f2803ce802bc69760e706fd991f4dc962 – the first release including this revision was MAME 0.240.

Can you please test the the official MAME 0.239 and 0.240 to confirm that the issue is present in 0.240 but not present in 0.239?

Also, can you please give brief instructions for how to test Pinyin input on the CEC Apple II clones?  I’m familiar enough with Pinyin, but not familiar with using these particular computers.

**Comment by cuavas** [comment] 2022-05-27 16:28
The previous merge into the feature branch before 3176606b60105e2cf3d9ec32674f9c609195145c was from 5dc5ab60b8f716f485575bedba5e8b2fb8544fa2, which actually predates MAME 0.239.  If the issue is present in MAME 0.239, can you please check to see if MAME 0.238 works correctly?

That gives a large range of candidate revisions for the regression.  Some that stick out:
* 49b9a4c8917dd62f220c9502ac894c2545a02905
* a402cdbafbe111a980e7b31a3813ae9c634f1731
* 2d140f79c54bd05720d4087da57db540764b899c
* d8e1b9c6f9c45213fdf6dc3f3eb3f3f0cf60ab40
* 423aa1c3260e135db68e73a760a93207d0da81bb
* 8b69ac5471f5502878df535b7306a5aae4a75f12

**Comment by cuavas** [comment] 2022-05-27 16:30
@rb6502 tagging you on this, as the CEC computers are in apple2e.cpp and you did the bank device to view conversion in that time frame.  Maybe you can spot something obvious.

**Comment by rb6502** [comment] 2022-05-27 17:00
Yeah, I'm already watching and I had the same idea.  I have no idea how Pinyin input works on these machines to test it though.

**Comment by DickyQi** [comment] 2022-05-27 19:13
How to Test Pinyin input:
mame ceci -skip_gameinfo -nosamples -window -nomax
F1 key to Chinese mode, then F2 switch pinyin method, type 'q' or 'f' or some other letter, it will appear some Chinese character at right bottom area as candidate. But if I using buggy version, then can't see any candidate, only beep.
Also I am only tracking apple2e.cpp, I found rev 2d140f79c54 is okay, but next rev d8e1b9c6f9c has issue.
PS: I tested rev 5dc5ab6 which is MAME 0.239, no such issue. and I tested rev f0ab44fe1c8 which is MAME 0.240 has that issue.

**Comment by cuavas** [comment] 2022-05-27 19:30
I just tested, it’s F7 to switch to Chinese mode for me, not F1.  For the benefit of @rb6502:
* Start the `ceci`
* Wait for the `]` prompt to appear
* Hit F7 to switch to Chinese mode, wait for `]` prompt again
* The input mode is displayed below the prompt – initially it will be “宇母” (Latin input)
* F1 switches to “宇母” (Latin input) and F2 switches to “拼音” (Pinyin Chinese input)
* In “拼音” mode you should be able to type Chinese transliterations and hit the numbers to accept candidates shown at the bottom right (e.g. typing “pin1yin5” produces “拼音”, or “zhong1guo3” produces “中国”)

**Comment by cuavas** [comment] 2022-05-27 19:36
@DickyQi thanks for the instructions on reproducing the issue.  I can reproduce it.

**Comment by DickyQi** [comment] 2022-05-27 19:57
Sorry for my typo. Yes F7 is switch to Chinese mode and F8 is switch back to ascii mode.
And in Chinese mode, F1 is Latin input, F2 is Pinyin input, F3 is GB2312 code input.

**Comment by rb6502** [comment] 2022-05-28 01:41
This is fixed in f7a8041.  Thank you for the report and the instructions!

**Closed by rb6502** 2022-05-28 01:41 UTC

**Comment by DickyQi** [comment] 2022-05-28 08:36
👍
