### ISSUE TITLE
Cannot load games through menu

### ISSUE THREAD

**Issue by Tauwasser** [mamedev/mame#2413] opened 2017-06-26 07:29 UTC
An exception pops up when trying to load any game as follows:

1. Start MAME
2. Select Machine (e.g. GameBoy)
3. Select an available Software (e.g. 4 in 1 (Euro, 4B-002))
4. Select any BIOS if applicable (e.g. DMG_vX)

The following message pops up:

---------------------------
MAME
---------------------------
Caught unhandled 23options_error_exception exception: Cannot specify software without specifying system

---------------------------
OK   
---------------------------

**Comment by Tafoid** [comment] 2017-06-26 10:04
Please indicate from what MAME version or Git revision your build is from so we can get a better understanding when/if a regression occurred.  With standard building, your binary will show the revision hash in the ** mame -help ** output.

**Comment by Tafoid** [comment] 2017-06-26 10:50
I can confirm this.  It regressed when applying source from #2341 to master.  My test binaries from June 4th, June 16 and June 17 made from that PR before it was applied to master all exhibit the same issue.

**Comment by npwoods** [comment] 2017-06-26 11:13
This seems to be a specific issue with the MewUI BIOS menu.  I don't believe that this affects systems without selectable BIOSes.  Fix coming soon.

**Comment by npwoods** [comment] 2017-06-26 11:43
PR submitted (#2416)

**Comment by Robbbert** [comment] 2017-07-30 06:20
This I believe has been fixed in the last cycle.

**Closed by Robbbert** 2017-07-30 06:20 UTC
