### ISSUE TITLE
issue in vs2022

### ISSUE THREAD

**Issue by claydonkey** [mamedev/mame#9665] opened 2022-05-01 17:50 UTC
https://github.com/mamedev/mame/blob/5753f5ef97c1dbba48c33d109d3a275f05794012/src/frontend/mame/infoxml.cpp#L439

I haven't submitted an issue before but here goes:
When compiling in vs2022 (v143), Windows SDK 10.0 the compiler complains that the source is referencing a deleted function (Compiler Error C2280)

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2280	'info_xml_creator::output::prepared_info &info_xml_creator::output::prepared_info::operator =(const info_xml_creator::output::prepared_info &)': attempting to reference a deleted function
        _Result = _STD forward<_Ty>(_Val);
                ^	frontend	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\future	314

I have change this line to:
	prepared_info &operator=(const prepared_info &) = default;
and it compiles fine now...

**Comment by cuavas** [comment] 2022-05-01 17:59
This is caused by a regression in the Microsoft C++ standard library.  They’ve made the `std::future` require the promise type to be copyable even if you don’t do anything requiring it to be copied.  See #9270 and #8688.  I believe this has already been reported to Microsoft, but I can’t find a link to the issue in a few minutes of searching.  Maybe @yz70s remembers which one it is.  You can apply a local workaround, but we really need more people to pressure Microsoft to stop breaking stuff.

**Comment by claydonkey** [comment] 2022-05-01 18:11
I'd like to PM you about something I am just starting to implement in Mame. I am fresh to Mame and I want to adhere to your framework guidelines and need a few pointers. Thanks

**Comment by cuavas** [comment] 2022-05-01 18:12
Better to post on a forum to discuss things.

**Comment by claydonkey** [comment] 2022-05-01 18:13
Thanks. I won't pollute this space anymore 👍

**Comment by cuavas** [comment] 2022-05-01 18:35
Some forums that MAME developers frequently read:
* https://reddit.com/r/MAME 
* https://forums.bannister.org/ (make sure you send an e-mail to confirm your registration, and be patient while it completes)
* https://www.mameworld.info/ubbthreads/postlist.php?Cat=&Board=programming
* https://forum.mamedev.org/

Another option is to open a draft pull request for discussion/feedback.

**Comment by invertego** [comment] 2022-05-04 19:08
> This is caused by a regression in the Microsoft C++ standard library. They’ve made the `std::future` require the promise type to be copyable even if you don’t do anything requiring it to be copied. See #9270 and #8688. I believe this has already been reported to Microsoft, but I can’t find a link to the issue in a few minutes of searching. Maybe @yz70s remembers which one it is. You can apply a local workaround, but we really need more people to pressure Microsoft to stop breaking stuff.

Here is what I have been able to gather:
- This isn't a regression in `<future>` (the bug goes back to the first version shipped with VS 2012).
- The build breaking code was introduced with #8300.
- The implementation does not require the type to be copyable, but it does require it to be assignable if it is default constructible.
- Therefore, this error could be addressed by making prepared_info movable instead of merely move constructible.
- The standard library bug has been fixed for non-default-constructible types (https://github.com/microsoft/STL/pull/2568), but fixing it for default constructible types is considered an ABI breaking change.
- ABI breaking changes aren't being considered until at least the next major release after VS 2022 (https://github.com/microsoft/STL/issues/169#issuecomment-864475056).

**Comment by cuavas** [comment] 2022-05-04 19:11
It *is* a regression in the Microsoft implementation of the future.  @npwoods actually developed that code building in Visual Studio, and it was broken by a subsequent Visual Studio update.

**Comment by npwoods** [comment] 2022-05-05 11:31
While I did the work on #8300 and I do the bulk of my debugging with Visual Studio, I can't rule out the possibility that the Microsoft C++ libraries always had this problem.

I do most "final" work on MinGW and there is a possibility that I might have "tightened" up the `prepared_info` definitions without verifying that it builds with Microsoft C++ libraries.

**Comment by cuavas** [comment] 2022-06-05 18:34
59a8e9dd5ae36be43e12998c003bc0c5dc56f0ff should work around this for now.

**Closed by cuavas** 2022-06-05 18:34 UTC

**Comment by invertego** [comment] 2022-06-06 04:50
> [59a8e9d](https://github.com/mamedev/mame/commit/59a8e9dd5ae36be43e12998c003bc0c5dc56f0ff) should work around this for now.

You may be interested to know that adding a default move assignment operator would also be sufficient and indeed may be preferable if you don't want the class to be copyable.

**Comment by invertego** [comment] 2022-06-06 07:12
Moreover, if you want to track the upstream bug, it's here: https://github.com/microsoft/STL/issues/2488

It had been closed prematurely but was reopened after I pointed this out. Bear in mind, it's been tagged vNext, which means there won't be a fix forthcoming until the next major release.
