### ISSUE TITLE
LUA screen draw functions can't access rightmost/bottommost pixels

### ISSUE THREAD

**Issue by antonioginer** [mamedev/mame#5736] opened 2019-10-14 11:17 UTC
As they are now, LUA functions `screen:draw_box` and `screen:draw_line` can't access the pixels on the rightmost column and on the bottommost row of the screen.

This happens because coordinate values can never reach 1.0f (either full width or height) since they are restricted to a maximum of : ` float(sc_width-1)) / float(sc_width) `and `float(sc_height-1)) / float(sc_height)`, in **luaengine.cpp**.

Changing those limits to 1.0f fixes the issue, but then the rightmost bottommost coordinate becomes (sc_width, sc_height), which doesn't seem fully correct.

E.g., if you have a 320x240 screen, in order to draw a box that covers the whole screen you'd need to draw_box (0, 0, 320, 240, ...), while (0 0, 319, 239, ...) would look more correct, but maybe I'm wrong. Just wondering before attempting a PR.

**Comment by oomek** [comment] 2019-10-14 11:35
When you want to draw 1 pixel in the top left corner you do it like that:
`scr:draw_box(0, 0, 1, 1, COLOR_WHITE, 0)`
the same goes for the bottom right corner:
`scr:draw_box(319, 239, 320, 240, COLOR_WHITE, 0)`
so it's logical that the x2y2 should not be restricted in the same way as the coords of the starting point.

**Comment by oomek** [comment] 2019-10-14 11:41
But that brings another danger, when you extend the range of just the x2y2 and you try to draw a square outside of the screen buffer ie:
`scr:draw_box(321, 241, 322, 242, COLOR_WHITE, 0)`
I believe you're still gonna draw that pixel in the bottom rigit, corner. Am I correct?

**Comment by oomek** [comment] 2020-04-23 04:04
Any ETA dor a fix?

**Comment by angelosa** [comment] 2021-02-10 00:08
From what I can tell from fiddling with the `draw_box` fn this looks by design hence wontfix. i.e. setting `0, 0, width, height` `width, height, 0, 0` covers full screen. Anything past that range is discarded.

**Comment by oomek** [comment] 2021-02-10 04:30
The recent LUA commits seemed to fix this issue

**Comment by angelosa** [comment] 2021-02-10 14:09
Thanks for confirming, closing.

**Closed by angelosa** 2021-02-10 14:09 UTC
Labels: Lua
