### ISSUE TITLE
Soul Calibur SPEED

### ISSUE THREAD

**Issue by BilonFullHDemon** [mamedev/mame#11987] opened 2024-01-30 01:16 UTC
### MAME version

MAME 0.261 in RetroArch

### System information

windows 11 64 bit i5 cpu, GTX card

### Emulated system/software

namco system 12

### Incorrect behaviour

 Speed 2 times too fast during fight in non interlaced mode and 2 times to slow in interlaced mode, overclocking down the cpu affects only the sound of the game

### Expected behaviour

Game should play normal speed like Tekken 3

**Comment by angelosa** [comment] 2024-01-30 09:52
Duplicate of https://mametesters.org/view.php?id=3040 , PS1 video PLL is very known to not be accurate in places (cfr. `psx:majodais` & `Gunnm: Martian Memory`), this bug report adds nothing of value so closing.

**Closed by angelosa** 2024-01-30 09:52 UTC
Labels: duplicate

**Comment by BilonFullHDemon** [comment] 2024-02-09 23:41
Yeah close it and leave it, that's all you do in MAME, total BS and garbage, that's what it is and by doing this you add nothing to MAME value.

**Comment by BilonFullHDemon** [comment] 2024-02-09 23:46
Game is in that state from 2017! That's all you can do about it? so disappointing...

**Comment by angelosa** [comment] 2024-02-26 15:38
What's your point? You didn't even covered the basics about searching in the two databases, you think creating a github account and requesting something already known from 2009 (two thousand and nine) that you didn't pay a single dime for will magically give devs the boost about fixing the framework faults?
From my PoV this is just one of the many monthly crybaby attempts about something YOU want, so either put up with some insightful info on that bug report (like the actual video timings that Arcade Soul Calibur PCB produces) or just shut up and wait patiently that others do it.

Pre-emptively locking here.
