### ISSUE TITLE
Current build tools are out-of-date and the purported maintainer is MIA

### ISSUE THREAD

**Issue by MooglyGuy** [mamedev/mame#7424] opened 2020-11-02 17:30 UTC
A month and a half ago, @mmicko claimed to be working on a new set of downloadable build tools for the project.

After an initial flurry of e-mails, he has gone completely incommunicado, leaving all of us (and our users) to fend for ourselves.

This is not an acceptable workflow. It's not acceptable that we should continue to be linking to non-functional, out-of-date build tools on our primary website, and it's neither acceptable to be holding out hope for someone who only appears about once a year, for a few days at a time, to manifest some updated version of the build tools.

I understand that sometimes real life takes the front seat, but we can all still let the rest of our purported team members know what's going on, and that we're going to be delayed. Just disappearing like this is not indicative of someone who is still invested in the ongoing success of the project.

Since our current, and only, solution is to install MSYS2 and a select set of packages to get MAME able to be compiled, then that is what we should be focusing on. Given that @Firehawke has numerous things on his plate already, someone else needs to step up to the plate and write a concise set of instructions on how to set up a working build environment for MAME given the current situation, and publish it to mamedev.org as expeditiously as possible, so that we do not continue to promote an objectively broken build environment as we're currently doing.

**Comment by mmicko** [comment] 2020-11-02 17:36
Hi, well I have created PR for that and it is merged, and I guess also
tested that time by Vas.

I have added instructions how to do it and that is part of PR :
https://github.com/mamedev/buildtools/tree/master/mame-essentials

I have no access to other parts of infrastructure so can not upload a new
toolchain, but it would not be a big deal for me to create one and send to
someone with access.

Regards,
Micko

**Comment by MooglyGuy** [comment] 2020-11-02 17:41
@mmicko Thank you for responding. I'm sorry that it had to come to the point of publicly calling you out, but there was a considerable amount of discussion that went on on the internal mailing list after your initial e-mail, and I did not see any responses. Can you please respond as necessary?

If this is all that is necessary to have a working standalone installer for build tools, that's excellent, but your continued presence on the list would be appreciated so that we can iron out any remaining issues or questions.

**Comment by mmicko** [comment] 2020-11-02 17:44
Sure, no worries. I will prepare a package, so the team can test, and then
make it public when all is confirmed fine.

**Comment by angelosa** [comment] 2021-02-04 12:32
Requirements for closing this are ...?

**Comment by cuavas** [comment] 2021-02-04 12:46
The tools package at the moment works.  I’ll do another one to remove 32-bit toolchain by default to reduce the size, since it’s not recommended  Next time around, I’ll record the steps used to build it.

**Closed by cuavas** 2021-02-04 12:46 UTC
Labels: spike
