### ISSUE TITLE
Buriki One (Hyper Neogeo 64) graphical issue

### ISSUE THREAD

**Issue by ReyVGM** [mamedev/mame#12833] opened 2024-09-30 10:03 UTC
### MAME version

0.270

### System information

Win10, 64bit, USA, US English, 16GB RAM

### Emulated system/software

Hyper Neo Geo 64 (hng64) - Buriki One (buriki)

### Incorrect behaviour

I'm only reporting this because the red warning at the beginning only mentions sound issues, and not graphical issues. I think that maybe the devs missed this when the Hyper Neo Geo 64's graphics were finally emulated completely.

Anyway, when you finish the game (with any character) and the credits are over, the game shows your character performing some moves. In the current MAME version, the character model shows no textures.

See video of how it should look versus the images of how it looks on MAME:
https://youtu.be/C2VFkVKSsXs?t=471

![1](https://github.com/user-attachments/assets/a5b86dc5-d431-4209-bed7-beca994065c7)

### Expected behaviour

The character model should have textures.

**Comment by angelosa** [comment] 2024-09-30 10:13
Duplicate of https://mametesters.org/view.php?id=8927

**Comment by cuavas** [comment] 2024-10-02 02:53
System is marked not working, and duplicate bug reports are bad form.

**Closed by cuavas** 2024-10-02 02:53 UTC
