### ISSUE TITLE
Incorrect/Inconsistent pixel scaling in GFX viewer tool

### ISSUE THREAD

**Issue by Superjustinbros** [mamedev/mame#9777] opened 2022-05-17 21:24 UTC
In older builds of MAME, the graphics viewer accessible through the F4 key would display sprites and tilesets used in the game with consistent pixel scaling, with every pixel at equal size. This made it useful for taking screenshots of the sprites to use in other projects quickly and efficiently (which I've done for sprite-ripping projects and sites for many, many years).

![unknown](https://user-images.githubusercontent.com/4167951/168832214-b1d26e55-6885-47f8-8fea-0169f4a44315.png)
In recent builds, however, the sprites are, by default, viewable at any scale and there is no method to lock the scaling to the exact 1x, 2x, 3x, and so on of earlier versions of MAME. This makes the sprites look rather sloppy at most resolutions, especially since there's no filtering applied to them.

For this, I'd like to suggest reverting to the older format of displaying sprites at fixed scales based on the resolution of the game window or screen.

**Comment by BPzeBanshee** [comment] 2022-05-18 05:00
Duplicate of my bug report: #9451.

As you yourself pointed out in the other bug report @cuavas , there's already a solution for this for the tilemaps that suits everyone, those options just need to be applied equally to the sprite viewer and that would suffice for the purposes listed here.

**Comment by cuavas** [comment] 2022-05-18 05:24
What’s suitable for viewing a tilemap isn’t the same as what’s suitable for viewing tiles, though.  The primary purpose of the tile viewer is to see at a glance whether the graphics decoding is working.  Fewer/more tiles per row controls suit that application.  Changing it to force integer ratios would mean you’d get very big jumps e.g. between 1x and 2x where it would halve the number of tiles on a line.  Forcing integer pixel scaling also won’t nicely when you want the number of tiles on a line to be a neat power-of-two to line up with addressing.

You’re demanding something that suits *you* at the expense of developers, while claiming it would suit everyone.

**Comment by BPzeBanshee** [comment] 2022-05-18 14:55
Demand's a strong choice word, but I digress. The current behaviour seemed like an oversight to me given the existing documentation, and the solution from a UX-design perspective obvious, but I guess I was wrong.

Should these issues be closed and alterations to the tilemap viewer be considered off-limits, then, if the current behaviour is considered working as intended? If so, I'm happy to close the original report I submitted and just keep using older MAME versions.

**Comment by happppp** [comment] 2022-05-18 16:00
Optional integer scaling for the gfxdecode viewer: yes please.
One of these issues may be closed, no need for duplicates.

rel: commit where gfxdecode integer scaling was removed: https://github.com/mamedev/mame/commit/4f495994c41cd2fbaf89c08f755e828ae3261828

**Comment by MooglyGuy** [comment] 2022-05-18 19:41
I tend to agree with @happppp on this one. Just because the viewer is "intended" for a particularly narrow use case doesn't mean that it can't be extended to be friendly to other use cases, as long as it doesn't come at the cost of the existing functionality. I'd be quite alright with implementing these changes myself once I have the time.

**Comment by cuavas** [comment] 2022-05-19 17:58
See #9783 for a proposed change that may make some people happier.

**Comment by cd4053** [comment] 2022-05-20 00:37
> See https://github.com/mamedev/mame/pull/9783 for a proposed change that may make some people happier.

Testing https://github.com/mamedev/mame/pull/9783

Run game: `mame shinobi -norc -rompath D:\roms -window`

Press F4 > Enter > left.
It jumps to color `3FF` and you can't press right to get back to 0, you have to keep pressing left until it counts down to zero again.
![image](https://user-images.githubusercontent.com/80734530/169425105-ea64bc45-60cf-4900-8681-31c38025fee3.png)

If you keep doing that, soon enough mame crash:

```
-----------------------------------------------------
Exception at EIP=00007ff6200ca204 (+0x200ca204): ACCESS VIOLATION
While attempting to read memory at 00000210584a0ff0
-----------------------------------------------------
RAX=0000000000000000 RBX=0000000000000020 RCX=0000000000001878 RDX=0000000000000800
RSI=0000000000000129 RDI=0000021068ea6e60 RBP=0000000000000000 RSP=000000ec7c2f9460
 R8=000002105cc59010  R9=0000000000000800 R10=0000000000000020 R11=000002104feea400
R12=0000000000000000 R13=0000000000001878 R14=0000000000000000 R15=000002105849ae10
-----------------------------------------------------
Stack crawl:
  000000ec7c2f9910: 00007ff6200ca204 (+0x200ca204)
  000000ec7c2f9980: 00007ff6200c7d98 (+0x200c7d98)
  000000ec7c2f99b0: 00007ff61fa44c36 (+0x1fa44c36)
  000000ec7c2f9ac0: 00007ff61fa3fd31 (+0x1fa3fd31)
  000000ec7c2f9af0: 00007ff61d85660f (+0x1d85660f)
  000000ec7c2f9b90: 00007ff61d97e692 (+0x1d97e692)
  000000ec7c2f9c70: 00007ff61ae6057f (+0x1ae6057f)
  000000ec7c2ff060: 00007ff61d85517d (+0x1d85517d)
  000000ec7c2ff320: 00007ff61fa6b364 (+0x1fa6b364)
  000000ec7c2ff470: 00007ff61fa6c806 (+0x1fa6c806)
  000000ec7c2ff4c0: 00007ff61d856467 (+0x1d856467)
  000000ec7c2ff860: 00007ff61ac4a95e (+0x1ac4a95e)
  000000ec7c2ff930: 00007ff6171b13b1 (+0x171b13b1)
  000000ec7c2ff960: 00007ff6171b14e6 (+0x171b14e6)
  000000ec7c2ff990: 00007ff9f5887034 (BaseThreadInitThunk+0x0014)
  000000ec7c2ffa10: 00007ff9f7862651 (RtlUserThreadStart+0x0021)
```
Even with symbols, I can't get a valid output. I might need to use `SANITIZE`.

**Comment by cuavas** [comment] 2022-05-20 02:11
That should be ready enough to fix.

**Comment by cuavas** [comment] 2022-05-20 04:34
@cd4053 that regression is fixed, and the code is more readable now.

**Comment by cd4053** [comment] 2022-05-20 06:40
@cuavas Thanks, I'll try it latter. If you don't hear from me, it means all OK.

**Comment by BPzeBanshee** [comment] 2022-05-21 07:38
Works great for my test cases, and improved on the old behaviour in that I can actually maximise the window and still adjust to get 1x tiles. Thank you to all involved.

@Superjustinbros have you had the chance to try a compiled build yet?

**Closed** 2022-05-21 07:59 UTC

**Comment by Superjustinbros** [comment] 2022-05-31 05:15
Pressing Shift + 0 works like a charm and displays the graphics the way they did in earlier builds.
