### ISSUE TITLE
Failed to run "make vs2017" due to error "make: 3rdparty/genie/bin/windows/genie.exe: Command not found"

### ISSUE THREAD

**Issue by KarenHuang2016** [mamedev/mame#6093] opened 2019-12-24 02:53 UTC
We are trying to build Mame on Window with VS2017. It failed to run  "make vs2017" due to error "make: 3rdparty/genie/bin/windows/genie.exe: Command not found". Could you please help to take a look?

According to the log file, genie.exe is generated at "3rdparty\genie\bin\windows\genie.exe". But we found the genie.exe is actually generated under path "3rdparty\bx\tools\bin\windows\genie.exe". 

**Repro steps:**
1. git clone https://github.com/mamedev/mame F:\gitP\mamedev\mame
2. Put msys2 under F:\gitP\mamedev\tools
3. set PATH=F:\gitP\mamedev\tools\msys64\usr\bin;F:\gitP\mamedev\tools\msys64\mingw64\bin;%PATH%
4. make vs2017

[mame.log](https://github.com/mamedev/mame/files/3997044/mame.log)

**Comment by p1pkin** [comment] 2019-12-25 11:42
make sure to use build tools package form https://www.mamedev.org/tools/ and follow instructions from "Installation" part ? (it is not enough to just set PATH)

in any way, it is not possible to build current MAME using VS2017 due to buggy MS compiler, you'll better try latest VS2019 which have them fixed afaik.
however it works OK if use VS2017 as IDE only, and compile code with msys2/gcc

**Comment by KarenHuang2016** [comment] 2019-12-26 08:59
@p1pkin Thanks for your response. I've tried to follow the instructions from "Installation" part. This issue still occurs.

**Comment by KarenHuang2016** [comment] 2019-12-27 03:01
Moreover, if we change the path of genie.exe to “3rdparty\bx\tools\bin\windows\genie.exe” in file F:\gitP\mamedev\mame\makefile line 1046 like below. We can run "make vs2017" successfully. 

We cannot find the reason why genie.exe is generated under the incorrect path. Do you have any ideas on how to debug this?

------------------------------------------------------
diff --git a/makefile b/makefile
index dbcea47412..c84340aa65 100644
--- a/makefile
+++ b/makefile
@@ -1046,7 +1046,7 @@ ifeq ($(NEW_GIT_VERSION),)
 NEW_GIT_VERSION := unknown
 endif
 
-GENIE := 3rdparty/genie/bin/$(GENIEOS)/genie$(EXE)
**+GENIE := 3rdparty/bx/tools/bin/$(GENIEOS)/genie$(EXE)**
 
 ifeq ($(TARGET),$(SUBTARGET_FULL))
 FULLTARGET := $(TARGET)

**Comment by p1pkin** [comment] 2019-12-27 04:26
sorry, I can't reproduce this issue, it works just fine here
here is example scenario:
- create D:\mame\ folder
- unpack msys64-32-2019-12-23.exe to D:\mame\
- run D:\mame\msys64\autorebase.bat
- unpack mame0217s.exe to D:\mame\
- create make_64vs.cmd file with contents:
call D:\mame\msys64\win32\env.bat
make.exe vs2017
- run it

and everything went just fine - after some time I see MSVC projects generated in D:\mame\build\projects\windows\mame\vs2017\

**Comment by KarenHuang2016** [comment] 2019-12-27 06:26
Thanks @p1pkin. Is there any make option which can help us to locate the issue? Or do you have any ideas on how to debug this? :)

**Comment by smf-** [comment] 2019-12-27 12:57
On 27/12/2019 03:02, Karen Huang wrote:
> We cannot find the reason why genie.exe is generated under the
> incorrect path. Do you have any ideas on how to debug this?

It's not being generated under the incorrect path, you have
3rdparty\bx\tools\bin\windows\genie.exe because it's stored in git.

https://github.com/mamedev/mame/tree/master/3rdparty/bx/tools/bin/windows
<https://github.com/mamedev/mame/tree/master/3rdparty/bx/tools/bin/windows>

But that isn't the latest and not the one we use (I have no idea why
it's in git). When working correctly you will end up with two copies

3rdparty\bx\tools\bin\windows\genie.exe
3rdparty\genie\bin\windows\genie.exe

So it sounds like for you it's not building it at all. It's the first
thing built when you run make vs2017. It could be something else in your
path that is causing it to fail to build?

GCC 9.2.0 detected
Creating obj/Release
Creating obj/Release/src/host
Creating obj/Release/src/host/lua-5.3.0/src
lapi.c
lauxlib.c
lbaselib.c
lbitlib.c
lcode.c
lcorolib.c
lctype.c
ldblib.c
ldebug.c
ldo.c
ldump.c
lfunc.c
lgc.c
../../src/host/lua-5.3.0/src/lgc.c: In function 'freeobj':
../../src/host/lua-5.3.0/src/lgc.c:691:7: warning: this statement may
fall through [-Wimplicit-fallthrough=]
   691 |       luaS_remove(L, gco2ts(o));  /* remove it from hash table */
       |       ^~~~~~~~~~~~~~~~~~~~~~~~~
../../src/host/lua-5.3.0/src/lgc.c:693:5: note: here
   693 |     case LUA_TLNGSTR: {
       |     ^~~~
linit.c
liolib.c
llex.c
lmathlib.c
lmem.c
loadlib.c
../../src/host/lua-5.3.0/src/loadlib.c: In function 'lsys_sym':
../../src/host/lua-5.3.0/src/loadlib.c:230:21: warning: cast between
incompatible function types from 'FARPROC' {aka 'long long int (*)()'}
to 'int (*)(lua_State *)' {aka 'int (*)(struct lua_State *)'}
[-Wcast-function-type]
   230 |   lua_CFunction f = (lua_CFunction)GetProcAddress((HMODULE)lib,
sym);
       |                     ^
lobject.c
lopcodes.c
loslib.c
lparser.c
lstate.c
lstring.c
lstrlib.c
In file included from ../../src/host/lua-5.3.0/src/lstrlib.c:22:
../../src/host/lua-5.3.0/src/lstrlib.c: In function 'str_pack':
../../src/host/lua-5.3.0/src/lauxlib.h:151:22: warning: this statement
may fall through [-Wimplicit-fallthrough=]
   151 |    ((B)->b[(B)->n++] = (c)))
       |    ~~~~~~~~~~~~~~~~~~^~~~~~
../../src/host/lua-5.3.0/src/lstrlib.c:1252:22: note: in expansion of
macro 'luaL_addchar'
  1252 |       case Kpadding: luaL_addchar(&b, LUA_PACKPADBYTE);  /* go
through */
       |                      ^~~~~~~~~~~~
../../src/host/lua-5.3.0/src/lstrlib.c:1253:7: note: here
  1253 |       case Kpaddalign: case Knop:
       |       ^~~~
../../src/host/lua-5.3.0/src/lstrlib.c: In function 'match':
../../src/host/lua-5.3.0/src/lstrlib.c:501:16: warning: this statement
may fall through [-Wimplicit-fallthrough=]
   501 |               s++;  /* 1 match already done */
       |               ~^~
../../src/host/lua-5.3.0/src/lstrlib.c:503:13: note: here
   503 |             case '*':  /* 0 or more repetitions */
       |             ^~~~
ltable.c
../../src/host/lua-5.3.0/src/ltable.c: In function 'luaH_get':
../../src/host/lua-5.3.0/src/ltable.c:545:23: warning: this statement
may fall through [-Wimplicit-fallthrough=]
   545 |     case LUA_TNUMFLT: {
       |                       ^
../../src/host/lua-5.3.0/src/ltable.c:551:5: note: here
   551 |     default: {
       |     ^~~~~~~
ltablib.c
ltm.c
lundump.c
lutf8lib.c
lvm.c
lzio.c
os_chdir.c
os_copyfile.c
os_getcwd.c
os_is64bit.c
../../src/host/os_is64bit.c: In function 'os_is64bit':
../../src/host/os_is64bit.c:16:20: warning: cast between incompatible
function types from 'FARPROC' {aka 'long long int (*)()'} to 'BOOL
(*)(void *, WINBOOL *)' {aka 'int (*)(void *, int *)'}
[-Wcast-function-type]
    16 |  WowFuncSig func =
(WowFuncSig)GetProcAddress(GetModuleHandle(TEXT("kernel32")),
"IsWow64Process");
       |                    ^
os_isdir.c
os_isfile.c
os_match.c
os_mkdir.c
os_pathsearch.c
os_rmdir.c
os_stat.c
os_ticks.c
os_uuid.c
path_getabsolute.c
path_getrelative.c
path_helpers.c
path_isabsolute.c
premake.c
premake_main.c
scripts.c
string_endswith.c
string_hash.c
Linking genie
Compressing src/mame/layout/j2reelcz.lay...

**Comment by startaq** [comment] 2020-10-06 13:58
This seems to work for everyone else, closing.

**Closed by startaq** 2020-10-06 13:58 UTC
