### ISSUE TITLE
Dreamcast CHDs created with chdman from the new Redump .cue/.bin format are not bootable in any DC emulator

### ISSUE THREAD

**Issue by oblivioncth** [mamedev/mame#6466] opened 2020-03-20 05:34 UTC
This may entirely be on the developers of said Dreamcast emulators to fix but I just wanted to make mamedev aware of this issue since this seems to affect all known Dreamcast emulators and therefore may be an issue with chdman (since it is one of the constant variables):

Recently Redump.org switched over to storing records of their Dreamcast games from .gdi/.bin to .cue/.bin. Although the data in a given cue sheet is formatted differently than in the same games corresponding .gdi, the information itself is nearly identical and has not changed at all (though admitedly I'm not entirely sure of the meaning of each flag value for GDIs as I can't find any documentation on the format).

Again, it may have to do with how the emulators implemented their CHD parser (i.e. they only used sample files converted from .gdi/.bin to .chd when developing it) but chdman does seem to handle .gdi in a particular manner over .cue as there are some substantial binary differences between the output when converting the same game using both forms of record. The CUE decedents seem to be slightly larger in general.

Other than some header information that I'm privy of, one main difference seems to be that only the GDI based CHD ouput has "PAD:0" before "PREGAP:0" for each track description.

**Comment by p1pkin** [comment] 2020-03-20 12:04
duplicate of #5866 , not sure if there anything new to add. also, this Issue tracker if not for feature requests.

**Comment by eadmaster** [comment] 2020-09-05 05:01
same issue here, chds are no longer booting, any workaround?

**Comment by KingKebab** [comment] 2020-10-08 21:05
@eadmaster : ReDump stopped to provide .gdi index files for many months. Your .gdi source isn't uptodate.
Some of them are missing and you can produce bad compressed CHD files.

FlyCast emulator can boot uncompressed "cue/bin" dumps. I don't understand why @rb6502 said in ticket #5866 "GD-ROMs are only supported from .GDI files.".

**Comment by rb6502** [comment] 2020-10-09 00:55
This issues section is for MAME and CHDMAN.  We do not support GD-ROMs from formats other than .GDI at this time.  Especially since Redump.org reportedly is having a war over who controls their site and database; it's not a great idea to rely on them for anything.

**Comment by KingKebab** [comment] 2020-10-09 03:19
@rb6502 I'm not involved into any internal politics. I was looking for a convenient and efficient tool to compress my Dreamcast optical disc dumps. And for now, like many people, I was always able to used chdman to store my optical disc dumps. I just note the limit of chdman isn't a technical issue around the index file format. This means another tool could make the change instead. It's not a dead end.

**Comment by p1pkin** [comment] 2020-10-09 09:17
@KingKebab it is not the question of politics, but because internal handling of GD-ROM images in CHD core tied to GDI format, it is not question of input "index file format" (you probably meant CUE or GDI), but these formats different in other things like tracks layouts, so CHD core will require serious rework to support that properly. and, as was said, currently there is no plans to support that.
however, I'd expecting this might be resolved (or at least will be easier to handle) in next major CHD update.

**Comment by oblivioncth** [comment] 2020-10-09 09:39
Well thanks for your reasoning. Hopefully if the next update makes support more feasible to implement then someone will eventually pick it up.

I was luckily enough to get my set over to CHD before the GDIs were dropped

**Comment by p1pkin** [comment] 2020-10-09 10:27
@oblivioncth 
> I was luckily enough to get my set over to CHD before the GDIs were dropped

technically, all the Redump's GDI images are BAD DUMPs (that's why they switched to custom extended CUE format instead), so not recommended to use.

**Comment by oblivioncth** [comment] 2020-10-09 11:09
> @oblivioncth
> 
> > I was luckily enough to get my set over to CHD before the GDIs were dropped
> 
> technically, all the Redump's GDI images are BAD DUMPs (that's why they switched to custom extended CUE format instead), so not recommended to use.

I had more recent dumps that were done with DIC after the format change and swapped the GDIs with the Cues to do the conversions. If the bad dumps were due to data issues only then its fine, but if the GDIs have incorrect offsets and lengths then that could be an issue. Haven't had any problems so far though

**Comment by eadmaster** [comment] 2020-10-09 12:39
> Haven't had any problems so far though

Same here, btw have you tried [this conversion tool](https://github.com/feyris-tan/gdidrop)?

**Comment by p1pkin** [comment] 2020-10-09 13:58
@oblivioncth  @eadmaster stop this, please. this is issue tracker, not discussion forum.

>  apparently, Redump is using a different GDI format than "General GDI",

the truth is: they even had no idea what GDI format really is, many people told them "you doing it wrong" but combo of giant ego and lack of tech knowledge not let them to understand that fact.
so, it took them about decade(!!!) until they finally accepted that fact and switched to another format - CUE, with custom extensions to hold GD-ROM images.

**Comment by KingKebab** [comment] 2020-10-11 22:16
@p1pkin : Thank you for all your interesting explanation. I think some other persons will land @mamedev/mame with the same issue. This dialog wasn't useless.

@eadmaster @oblivioncth : I wrote a DOS command line tool to recreate the .gdi index file from a cue/bin dump to make a compressed CHD file. And I shared some observations about .cue files. Some Dreamcast dumps from ReDump aren't only GD-ROM dump. That's the matter. Anybody is welcome. You can take a look here : https://forum.batocera.org/d/4668-dreamcast-emulators-and-the-chd-compressed-file-format-support

**Comment by nhand42** [comment] 2020-11-01 13:00
I've added preliminary support to chdman for Redump's bin/cue used for Dreamcast dumps. Successfully tested with Crazy Taxi and gets the same result as bin/gdi. Over the next few days I'll test all the Redump images I have and tidy up the code before submitting upstream. Please provide feedback as I'm not very familiar with the GDI format so I've based the code on the existing bin/gdi parser.

https://github.com/nhand42/mame/tree/redump_dreamcast_cue_support

**Comment by nhand42** [comment] 2020-11-07 12:16
Support for Redump cue/bin has been improved following feedback from the maintainers. The original pull request produced a layout similar to Redump GDI layout which I now understand is flawed. The code now produces a layout identical to TOSEC GDI dumps which is far superior. The CDDA tracks are now ripped from index1 rather than index0 which is a GDI specific thing. Also special GDI layouts as used by Shenmue and Bust-a-Move are now correctly handled. 

I've tested several dozen titles over the past few days and I'm happy with the results. Pull request has been submitted upstream for maintainers to review.

**Comment by oblivioncth** [comment] 2020-11-07 16:33
Excellent, nice work.

Hopefully 100% compatability can be confirmed/achieved in due time and this issue closed.

**Comment by angelosa** [comment] 2021-02-05 13:35
@p1pkin can this be closed then? Or I have to assume that requirement here is **Mil-CD support in DC**?

**Comment by mspykerez** [comment] 2021-06-06 04:11
> @p1pkin can this be closed then? Or I have to assume that requirement here is **Mil-CD support in DC**?

So is chdman currently supporting MIL-CD or not?

**Comment by p1pkin** [comment] 2021-06-06 10:38
> 
> 
> @p1pkin can this be closed then? Or I have to assume that requirement here is **Mil-CD support in DC**?

yes, this is resolved and may be closed now

> So is chdman currently supporting MIL-CD or not?

current CHD core doesn't supports multi-session CD, so no

**Closed by p1pkin** 2021-06-06 10:38 UTC
