### ISSUE TITLE
DirectX 12 in BGFX = less input lag

### ISSUE THREAD

**Issue by oomek** [mamedev/mame#1944] opened 2017-01-09 00:58 UTC
Would it be possible to allow to run Mame in BGFX DirectX 12 mode? This would allow to reduce the input lag by 2 frames by utilizing a new borderless immediate iFlip mode introduced in DX12

**Comment by rb6502** [comment] 2017-01-09 02:33
BGFX has WIP DX12 support, I don't know if it works yet.  You'd have to ask Branimir.

**Comment by oomek** [comment] 2017-01-09 03:08
BGFX indeed has, but it's not exposed in mame, you have to modify int renderer_bgfx::create()
in drawbgfx.cpp to make it allow to switch to dx12. I tried it, but I get dx stack errors when I try to run it. I suppose some other changes need to be done, to make it work.

**Comment by belegdol** [comment] 2019-11-01 07:16
Initial support is in 0.215, with the one currently known issue is that it crashes on exit.

**Comment by chrispy-snps** [comment] 2021-01-01 17:59
@belegdol - how do I enable this support?

**Comment by chrispitude** [comment] 2021-01-01 18:01
@belegdol - how do I enable support for this?

**Comment by belegdol** [comment] 2021-01-01 18:55
-video bgfx -bgfx_backend dx12

**Comment by chrispitude** [comment] 2021-01-02 15:00
@belegdol - thanks! I got excited and thought you meant that @oomek 's request was implemented. Still, now that we have proper DX12 support in BGFX,

I wasn't sure what "borderless immediate iFlip mode" was, but I found this, which is some pretty good reading:

https://devblogs.microsoft.com/directx/dxgi-flip-model/

Maybe we can stir up some activity on this request now. I suppose the first task would be to have this issue assigned to someone, since it's currently unassigned. Any suggestions on how to do that?

**Comment by MooglyGuy** [comment] 2021-01-02 15:19
By doing exactly what you just did. Having a look now.

**Comment by MooglyGuy** [comment] 2021-01-02 15:29
Have you actually tried what @belegdol suggested?

MAME supports (and has for at least a few versions now) initializing BGFX in D3D12 mode, as shown here in drawbgfx.cpp:

```		else if (backend == "dx12" || backend == "d3d12")
		{
			init.type = bgfx::RendererType::Direct3D12;
		}```

From looking at the version of BGFX that is in our 3rdparty directory, it appears that BGFX will attempt to bring up the D3D11 renderer with DXGI_SWAP_EFFECT_FLIP_DISCARD, and will attempt to bring up the D3D12 renderer with DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL, both of which are suggested by the specific article you linked to.

This is something that will only work on Windows 10, but if that is the OS you're running, then it seems like it should work.

Let us know, @chrispitude, so that I can either close this issue or do further investigation.

**Comment by chrispitude** [comment] 2021-01-02 20:53
I used [the Sysinternals Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) program to check which DirectX DLLs are used by MAME. To do this, enable **View > Lower Pane View**, then select **View > Lower Pane View > DLLs** to show the DLLs loaded by the selected process.

By default, MAME/BGFX uses DirectX 11 if `bgfx_backend` is undefined or set to `default`. However, I confirmed that it does indeed use DirectX 12 when `bgfx_backend` is explicitly set to `d3d12`.

I have no idea what the actual lag/responsiveness merits are of DXGI_SWAP_EFFECT_FLIP_DISCARD versus DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL, but between my DLL confirmation and your code inspection, it seems that OP's request is satisfied.

**Comment by MooglyGuy** [comment] 2021-01-02 21:39
In light of this latest information, I'm closing this unless there's any evidence that the updated DX12 functionality does not provide the lower-lag experience advertised.

**Closed by MooglyGuy** 2021-01-02 21:39 UTC
