### ISSUE TITLE
chdman 0.263 error does not compress dreamcast games

### ISSUE THREAD

**Issue by CorvuzSoli** [mamedev/mame#12081] opened 2024-02-28 22:52 UTC
### MAME version

0.263

### System information

Windows 10

### Incorrect behaviour

chdman 0.263 error does not compress dreamcast games, I tried with version 0.262 and it also has that problem.

### Expected behaviour

 I tried with version 0.261 and I had no problems with it.

### Steps to reproduce

C:\Users\xxxx\Desktop\chdman> for /R %i in (*.cue *.gdi *.iso) do chdman createcd -i "%i" -o "%~ni.chd"

C:\Users\xxxx\Desktop\chdman>chdman createcd -i "C:\Users\xxxx\Desktop\chdman\Star Wars - Episode I - Racer (USA).cue" -o "Star Wars Episode I - Racer (USA).chd"
chdman - MAME Compressed Hunks of Data (CHD) manager 0.263 (mame0263)
Output CHD: Star Wars - Episode I - Racer (USA).chd
Input file: C:\Users\xxxx\Desktop\chdman\Star Wars - Episode I - Racer (USA).cue
Input tracks: 5
Input length: 122:02:00
Compression: cdlz (CD LZMA), cdzl (CD Deflate), cdf1 (CD FLAC)
Logical size: 1,344,333,888
Error reading input file (C:\Users\xxxx\Desktop\chdman\Star Wars - Episode I - Racer (USA) (Track 4).bin)'
exception occurred: std::exception
Error during compression: Input/output error

**Comment by 987123879113** [comment] 2024-02-29 03:57
Looks like it broke with https://github.com/mamedev/mame/commit/b75b8d80e87c4bfb7d040385cb09b6f24eafe604. 

Someone made a comment in the related issue last month about the same problem it seems. https://github.com/mamedev/mame/issues/11903

**Comment by 987123879113** [comment] 2024-02-29 04:21
The exact cause seems to be this code here. 

https://github.com/mamedev/mame/blob/1615b8551a3a73532ac234973cfb04dd8ed98ba4/src/lib/util/cdrom.cpp#L2889-L2905


```
trk 1: 603 frames @ offset 0, pad=0, split=0, area=0, phys=0, pregap=0, pgtype=0, idx0=0, idx1=0, (true 603)
trk 2: 44397 frames @ offset 0, pad=43721, split=0, area=0, phys=603, pregap=150, pgtype=7, idx0=0, idx1=150, (true 676)
trk 3: 311304 frames @ offset 0, pad=0, split=0, area=1, phys=45000, pregap=0, pgtype=0, idx0=0, idx1=0, (true 311304)
trk 4: 751 frames @ offset 352800, pad=150, split=75, area=1, phys=356304, pregap=150, pgtype=7, idx0=0, idx1=150, (true 601)
trk 5: 192095 frames @ offset 529200, pad=0, split=0, area=1, phys=357055, pregap=225, pgtype=1, idx0=0, idx1=225, (true 192095)
```

It's setting the offset values for tracks 4 and 5 to non-zero values, so when it tries to read track 4 it seeks to offset 352800 before reading data. But 352800 is the end of the file so it returns 0 bytes read, resulting in the error.

https://github.com/mamedev/mame/blob/1615b8551a3a73532ac234973cfb04dd8ed98ba4/src/tools/chdman.cpp#L454-L463


Maybe @rb6502 will know how to handle this case properly? I don't know much about Dreamcast stuff so I don't know why this code exists and what could break by removing it.

**Comment by rb6502** [comment] 2024-02-29 16:55
bin/cue support for GD-ROM discs came from external patches, and as was noted this specific regression was introduced by @alucryd so they would be the best suited to address it.

**Comment by alucryd** [comment] 2024-02-29 17:20
I would not, as I stated when submitting the patch, I don't speak C++ and I barely understood what I was doing, my limited testing seemed to work so I submitted it for review.

**Comment by 987123879113** [comment] 2024-03-03 11:24
Should be fixed in https://github.com/mamedev/mame/pull/12087. 

@alucryd The above PR should also fix the issue you were trying to fix in the previous PR as well. Would you mind giving it a test just to verify if you get a chance?

**Comment by alucryd** [comment] 2024-03-03 12:03
Thanks! Will give it a try later today. I have some oxyromon users I can ask for help as well.

**Closed** 2024-03-06 15:15 UTC
