### ISSUE TITLE
Crashes/regressions with new BGFX

### ISSUE THREAD

**Issue by ajrhacker** [mamedev/mame#5956] opened 2019-11-24 02:27 UTC
1. In any driver which configures a rgb32/argb32 screen, trying to change any of the Brightness, Contrast or Gamma sliders crashes MAME immediately. It doesn't crash if the `-gamma` option is set to 0.9 or less or 1.1 or greater.
2. screen_device::set_color no longer seems to have any effect, whether the screen bitmap is ind16 or rgb32.
3. (Minor) Before the loading screen comes up, an image left over from a previous instance of MAME may be displayed. This could lead to highly embarrassing situations for users if these images come from *some* kinds of games...

**Comment by MooglyGuy** [comment] 2019-11-24 04:49
Thanks for the report. In the future, consider reporting these sorts of issues sooner than the literal day on which we go into code freeze prior to a release.

**Comment by cuavas** [comment] 2019-11-24 05:03
When making a big change that affects every driver, you need to follow through on it.  You can't just hope that other people are going to do comprehensive testing for you.  We don't have a full-time QA team or acceptance testing.

It's also unfair to blame it on it taking time for others to notice when an issue like the breakage when running LaserDisc games (#5830) sits open for weeks without any acknowledgement at all.

**Comment by MooglyGuy** [comment] 2019-11-24 05:08
It hasn't been acknowledged because I haven't been able to reproduce it at all. As far as I'm concerned it may as well not be happening. If you can consistently repro the crash, then great, get me more info like local variable state. Otherwise, fuck off.

**Comment by belegdol** [comment] 2019-11-24 08:12
Looks like I can reproduce the crash on brightness change, I will try to provide full backtrace later today. Is output of gdb's bt full going to be sufficient?

**Comment by belegdol** [comment] 2019-11-24 14:13
Here is the backtrace when attempting to change invqix' contrast. I ran 19a09406a63005cc470695684a57a6e4e36196cb as follows:
```
./mame64d -rompath /mnt/openmediavault/emu/mame/roms/ -nomaximize -window -video bgfx -bgfx_backend vulkan invqix
```
```
#0  0x0000000000759a64 in chain_manager::update_screen_textures (this=0x2deea80, view=<optimized out>, 
    starting_prim=<optimized out>, window=...) at ../../../../../src/osd/modules/render/bgfx/chainmanager.cpp:509
#1  0x00000000006f634d in renderer_bgfx::draw (this=0x31eaf20, update=<optimized out>) at ../../../../../src/emu/render.h:360
#2  0x00000000006cf4f7 in sdl_window_info::update (this=0x2dd74f0) at /usr/include/c++/9/bits/unique_ptr.h:352
#3  sdl_window_info::update (this=0x2dd74f0) at ../../../../../src/osd/sdl/window.cpp:560
#4  0x00000000006caba5 in sdl_osd_interface::update (this=0x7fffffffcfd0, skip_redraw=<optimized out>)
    at ../../../../../src/osd/sdl/video.cpp:108
#5  0x0000000001d4ec94 in video_manager::frame_update (this=0x480cff0, from_debugger=from_debugger@entry=false)
    at ../../../../../src/emu/video.h:54
#6  0x0000000001d0bf5d in screen_device::vblank_begin (this=0x2ef1760) at ../../../../../src/emu/machine.h:178
#7  0x0000000001d0ed75 in screen_device::device_timer (this=0x2ef1760, timer=..., id=<optimized out>, param=<optimized out>, 
    ptr=<optimized out>) at ../../../../../src/emu/screen.cpp:959
#8  0x0000000001d03bf6 in device_t::timer_expired (ptr=<optimized out>, param=<optimized out>, id=<optimized out>, timer=..., 
    this=<optimized out>) at ../../../../../src/emu/device.h:609
#9  emu_timer::device_timer_expired (timer=..., ptr=<optimized out>, param=<optimized out>)
    at ../../../../../src/emu/schedule.cpp:318
#10 0x0000000001d052aa in delegate_base<void, void*, int>::operator() (this=<optimized out>, this=<optimized out>, 
    args#1=<optimized out>, args#0=<optimized out>) at ../../../../../src/lib/util/delegate.h:506
#11 device_scheduler::execute_timers (this=<optimized out>) at ../../../../../src/emu/schedule.cpp:908
#12 device_scheduler::timeslice (this=this@entry=0x7fffffffc2d0) at ../../../../../src/emu/schedule.cpp:545
#13 0x0000000001cabab8 in running_machine::run (this=this@entry=0x7fffffff6db0, quiet=quiet@entry=false)
    at ../../../../../src/emu/machine.cpp:367
#14 0x00000000007b8796 in mame_machine_manager::execute (this=this@entry=0x2dcf6e0)
    at ../../../../../src/frontend/mame/mame.cpp:261
#15 0x00000000008565dc in cli_frontend::start_execution (this=0x7fffffffcdc0, manager=0x2dcf6e0, args=...)
    at ../../../../../src/frontend/mame/clifront.cpp:267
#16 0x00000000008567ae in cli_frontend::execute (this=this@entry=0x7fffffffcdc0, 
    args=std::vector of length 10, capacity 10 = {...}) at ../../../../../src/frontend/mame/clifront.cpp:283
#17 0x00000000007b6a38 in emulator_info::start_frontend (options=..., osd=..., args=std::vector of length 10, capacity 10 = {...})
    at ../../../../../src/frontend/mame/mame.cpp:392
#18 0x000000000051f8eb in main (argc=<optimized out>, argv=<optimized out>) at ../../../../../src/osd/sdl/sdlmain.cpp:217
```
The local variables are (obtained with info-locals):
```
palmem = <optimized out>
needs_conversion = <optimized out>
mem = <optimized out>
chain = <optimized out>
tex_width = <optimized out>
screen_name = "screen0"
dst_format = bgfx::TextureFormat::BGRA8
prim = @0x606f240: {m_prim = 0x604f680, m_screen_width = 241, m_screen_height = 321, m_quad_width = 241, m_quad_height = 321, 
  m_tex_width = 257, m_tex_height = 241, m_rowpixels = 640, m_palette_length = 256, m_flags = 532518}
texture = 0x606f390
palette = 0x0
src_format = <optimized out>
source_name = "source0"
full_name = "source0"
tex_height = <optimized out>
screen_index = "0"
palette_name = "palette0"
pitch = 2560
screen = 0
```
The full backtrace is attached.
[gdb.txt](https://github.com/mamedev/mame/files/3883660/gdb.txt)

**Comment by MooglyGuy** [comment] 2019-11-24 14:41
Points 1 and 2 should be fixed, @ajrhacker . Once verified fixed, please close this issue and create a separate one for the lack of render target clearing.

**Comment by cuavas** [comment] 2019-11-24 15:08
Brightness/gamma/contrast works, screen colour works.  Render target not clearing seemed to happen after the bgfx update itself, not the other changes.

**Closed by cuavas** 2019-11-24 15:08 UTC

**Comment by ajrhacker** [comment] 2019-11-24 15:24
I can confirm that issues 1 and 2 are now fixed.

**Comment by rb6502** [comment] 2019-11-24 15:26
Agreed, for me the render target not clearing was from an upstream bgfx sync.
