### ISSUE TITLE
Add info to XML

### ISSUE THREAD

**Issue by AntoPISA** [mamedev/mame#615] opened 2016-02-09 17:00 UTC
I think, before it is definitively denied the opportunity to compile only MAME arcade or just MESS, it should be added to the xml voice  "IsArcade", just like "IsMechanical" or "IsDevice". With more than 30,000 machines currently present, a new filtration system would be very useful (especially for front-end, but not only).

Also useful to add entries "Arcade" and "Not Arcade" in the new UI.

**Comment by galibert** [comment] 2016-02-09 17:18
Like, no.

**Comment by AntoPISA** [comment] 2016-02-09 18:01
Excuse me but I have not figured out if your comment is positive or negative ...

**Comment by galibert** [comment] 2016-02-09 18:42
Very negative.

**Comment by felipesanches** [comment] 2016-02-09 19:01
Could you ellaborate on that? I can see both pros and cons to this proposal.
While I'd like to hear @galibert 's rationale, here's mine:

* Pros:

Metadata is very valuable. As a general principle I would be very supportive of adding a richer set of metadata fields for all devices. Because it helps us sort things, categorize them, and make richer and more meaninful queries to the database. 

I've been wondering about the possibility of employing metadata markup techniques such as the ones used for Linked Data with the objective of improving the user experience on places like the Internet Archive's Arcade Museum, for instance (or really, for any user of the javascript transpiled builds of specific MAME drivers). I think that's definitely a fruitful area for further research if one is truly concerned about enhancing historical preservation efforts.

* Cons:

Having the ability to "filter-out" stuff makes it easier to ship partial builds which potentially fragment the project and which likely weakens the historical preservation of the devices emulated by the less popular drivers. So I would only support doing so, if that's done as part of a larger effort towards much richer metadata, instead of simply to allow incomplete builds.

**Comment by AntoPISA** [comment] 2016-02-09 20:11
In my opinion are more pros than cons.
More information (or more details) is always positive. I do not understand this ostracism.
@galibert: Can you explain it better?

**Comment by rb6502** [comment] 2016-02-09 20:50
Ever since the projects were merged, certain people have been seeking to deny the hard work of many devs (myself included) on the "former MESS drivers" by stripping them right back out of MAME again.  We consider this behavior to be deeply insulting, and we will not provide people the means with which to do it on a silver platter.

**Comment by AntoPISA** [comment] 2016-02-09 20:59
I fully understand your point of view (I love the MESS, I consider it interesting). In fact I try in my small way, to contribute as much as possible (unfortunately I'm not a programmer).
I was only useful, before eliminating the ability to compile MAME without MESS, they can at least distinguish them in the new UI. Just this.

Anyway thanks.

**Comment by mr-t-guru** [comment] 2016-02-09 22:31
there is no MESS. it is MAME and includes everything.
Forget MESS, it's history.

**Comment by AntoPISA** [comment] 2016-02-10 11:20
Forget...

Thanks for your answers.

**Comment by u-man74** [comment] 2016-02-10 12:58
@Belmont: I totally agree with you, that noone should disrespect the tremendous work on former MESS drivers, but i dont think that people deny the hard work, it is more that supporting MESS, can also considered as hard work on the frontend developer side and please dont come with qmc2. 
In particular i dont like that frontend devs are forced to support it and this is a wrong approach in my eyes. It looks more like a personal dispute rather than a logical step. More meta-data would eventually help frontend devs to fully support MAME. If i look at GameEx for example, it supports the MESS side of MAME now, but it is still very time-consuming to configure a meaningful setup, as a user needs to setup each machine individually and even if this is done, you would need mapfiles for each machine for proper name-handling.
I think it would be much better, to invest more time and work to make it easier for 3rd party devs, as doing exactly the opposite. Doing steps together to reach the goal, you know.
I am really scared to write this, as i dont want to upset you or others here, risking to be not heard anymore. I just want to tell my thoughts and i am open to hear your opinions.

**Comment by galibert** [comment] 2016-02-10 13:12
That's bullshit.  Why is it bullshit?  Because there's zero configuration
difference between neogeo MVS and AES, between cps2 arcade and cps2
exchanger, and in general between arcade and consoles.

What makes a configuration difference is the inputs.  It's entirely
different to configure the inputs for "standard" arcade games, mahjong
games (20-odd keys), keyboardmania (24-key piano keyboard), dance dance
revolution (pad on the ground), typing of the dead (full 100+ key keyboard)
or prop cycle (exercise bike).  Guess what, all of these are arcade games.
And we do give the input information in the xml.

So no, filtering mame vs. mess is just taking a piss on our work.

  OG.

**Comment by mr-t-guru** [comment] 2016-02-10 13:24
hahahah! so it's the same moron as the other thread now stirring up more pointless shit.
should have left the other thread locked and banned him.
now he's going to keep going on and on and on (at least until he's banned) and I'm just going to laugh and say I told you so....

**Comment by u-man74** [comment] 2016-02-10 13:35
@mr-t-guru: i dont know who the real moron is here :) , but you wrote false arguments in the other thread.
@galibert: you didnt understand my last post. it seems that you dont realize that most frontends where written at a time where only MAME existed and they struggle right now, to make it as useful and easy as it was before and i dont mean any input-stuff with this (you would do this externally with MAME anyway).

**Comment by galibert** [comment] 2016-02-10 13:48
Why do they struggle?  There's almost nothing in the mess-added systems
that doesn't exist in the arcade ones.  And anything problematic (unhandled
inputs, slots, softlists) is indicated in the xml.  A frontend that handles
the whole of mame and that can't cope with any mess driver makes zero sense.

**Comment by u-man74** [comment] 2016-02-10 14:05
As i told before, there is no problem to get machines running. The problem is to set them up. Nearly all frontends start emulators via a commandline and in case of GameEx, you would need many different commandlines to start the machines, but you can only have one commandline per emulator. 
So a user need to setup each machine as a seperate emulator, even if it is just one MAME. It becomes more complicated, if you want artwork support for the machines. 
Prior GameEx had total control of MAME and was a rich featured frontend for it (it is still, at least for the arcade part) but these features are gone in the case of MESS. I am sure, that Tom Speirs and Headkaze will find a solution, but thats the current state.

**Comment by rb6502** [comment] 2016-02-10 14:21
QMC2 manages to keep up with everything we throw, so the inability of for-profit frontends like GameEx to do so frankly reflects poorly on them, not on us.

**Comment by balr0g** [comment] 2016-02-10 14:21
@u-man74 that's more of an issue on the frontend :-/ Don't forget that the lines between "MAME" and "MESS" machines are often arbitrary and blurred — e.g. there are arcade machines that use cartridges and whatnot.
If there's metadata we are lacking that would help frontends support machines better, it would be useful to know about it, but general machine-type classifications are **arbitrary** and problematic in the long term.

**Comment by mr-t-guru** [comment] 2016-02-10 14:22
We are not stupid, we have known the front end in MAME has sucked for many years.
Over the last week or two work has begun on updating the MAME front end to support the current situation by one of our new members who has some enthusiasm about front ends. 
This isn't the end, the front end will continue to be enhanced and changed for some time until everyone is happy.
You should probably just wait and see what happens, rather than whine about it and annoy the devs who are trying to make it better.

**Comment by balr0g** [comment] 2016-02-10 14:23
As @rb6502 says, this is more likely an issue on the side of the frontend developers not being interested in putting in the extra effort to properly support things they don't consider "arcade" — an arbitrary distinction.

**Comment by rb6502** [comment] 2016-02-10 14:35
It's actually a bit worse than that.  GameEx supports console games, they just haven't ever supported MESS/MAME for them.

**Comment by u-man74** [comment] 2016-02-10 15:31
And i am not stupid too :)  annoying yes :( but thats just a pov nothing else.
@Belmont: GameEx is non-profit and you can always use a free version, for extra features that are mostly media center related (that are in no way including MAME) you would need to buy a license.
QMC2 is the worst example you can bring in here, especially comparing vs. GameEx, which is way older and that is the crux of matter.
It is absolutely not true, that GameEx didnt support MESS... it did since UME, merely not as rich featured as MAME, just FYI and as described previously.
Tom Speirs and the team, is willing to support MAME, more than you all are aware of ;) .
@balr0g: 
I will try my best, to exactly find out, how you all could help them and will speak to them tonight. Who would they need to contact, if they have collect all the answers? So that Tom itself can contact the person, as i have learned my lesson from the past :) .
Believe me, i am very glad to hear, that we can discuss things, like nomal people here.
Thank you so far, as this is the right approach and everyone will benefit from it.

**Comment by galibert** [comment] 2016-02-10 15:32
Megatech, neogeo and stv uses softlists, you know?

**Comment by stilett0** [comment] 2016-02-10 17:14
Once again, @u-man74 please stop being the go-between between MAMEDev and other teams. Just... stop. The outside teams will reach out to us if they feel the need, or if MAMEDev feels the need, MAMEDev will reach out to them. Your trying to "interpret their wishes" in particular seems to specifically be problematic.

**Comment by stilett0** [comment] 2016-02-10 17:31
Fact of the matter:
- MESS is part of MAME now
- any frontend not capable of handling all of the needs of console/computer emulation and configuration is now considered by MAMEDev to be poorly designed and outdated.
- if a frontend developer can't handle the updating this requires upon their frontend, then they've become used to the relative stability of the MAME command-line and INI settings over the last 8 years or so and have forgotten the churn of the early days as new features winked in and out.
- the general plan requires, at least over the next few years, new INI settings and command-line settings disappearing and reappearing and adding and modifying much more rapidly then they used to. So, as a frontend developer, get back used to the old days of churn. Monitor MAME closely - this isn't necessarily a MESS thing. If a frontend developer can't deal with the game of updates, then they may as well quit development now.

Get with the program. :)

**Comment by AntoPISA** [comment] 2016-02-12 15:52
I would say that Stiletto has closed permanently this discussion.

Thank you all!

**Closed** 2016-02-12 15:52 UTC
