### ISSUE TITLE
emscripten_set_main_loop_timing

### ISSUE THREAD

**Issue by summerock** [mamedev/mame#2794] opened 2017-11-12 16:37 UTC
I'm trying to compile the emscripten js for cps3, but when i run it on the browser i keep getting  the follow error:

`emscripten_set_main_loop_timing: Cannot set timing mode for main loop since a main loop does not exist! Call emscripten_set_main_loop first to set one up.`

Does anyone know how to fix it? I'm only getting it for CPS3. Thanks.

**Comment by DopefishJustin** [comment] 2017-11-13 00:38
I am able to reproduce this. Haven't had time to look into the cause yet but CPS3 uses a DRC CPU core which has tended to cause problems with Emscripten builds in the past.

**Comment by DopefishJustin** [comment] 2018-07-15 04:42
The loop timing error is just a symptom of the emulation having crashed. The crash is fixed with 370a411987f3501de1bb595beac9801dc8671a47 although to actually run a CPS3 game I had to compile with a larger memory size by adding ARCHOPTS="-s TOTAL_MEMORY=536870912" to the make command. Hopefully there will be a better way of dealing with that at some point.

**Closed by DopefishJustin** 2018-07-15 04:42 UTC
