### ISSUE TITLE
HP9k370 HP-UX 9 system fails to boot from SCSI device

### ISSUE THREAD

**Issue by beario-bear** [mamedev/mame#12611] opened 2024-07-23 16:11 UTC
### MAME version

0.267

### System information

OS: Ubuntu ‘Jammy’ 64-bit, kernel 6.5.0-41-generic
Locale: en_GB.UTF-8
RAM: 16GB
CPU: Intel(R) Core(TM) i5-10500T CPU @ 2.30GHz
GPU: Intel UHD graphics 630

### Emulated system/software

hp9k370

### Incorrect behaviour

Upon starting HP-UX 9.10, the kernel panics with ‘panic: rootmount cannot mount root’ from emulated SCSI device.

![image](https://github.com/user-attachments/assets/0dae09fb-9cdf-4053-bccf-93b72d844650)

### Expected behaviour

Upon starting HP-UX 9.10, the kernel correctly recognizes the attached SCSI disk and boots normally.

![image](https://github.com/user-attachments/assets/cdfb67c0-5b13-4e5a-be96-50fe95beab04)

(boot is shown here mid-process and continues normally from this point)

### Steps to reproduce

Launch MAME with any version greater than or equal to 0.255, emulating hp9k370, with a known good working installation of HP-UX 9.10.

Command being used is:

`mame -video opengl hp9k370 -sl2 98643 -hard ./hpux9k370n3.chd -window -mouse -uimodekey DEL -rompath ./roms -cfg_directory ./cfg -nothrottle`

Original HP-UX build was made from scratch, following the guide at https://wiki.mamedev.org/index.php/Driver:HP300, using MAME 0.235 at the time

### Additional details

Have confirmed this issue on Ubuntu Jammy, Debian 11, Debian 12, and on different physical hardware.

This is tested with a known-good disk image, and in MAME 0.254 and earlier, the emulation is fully functional.

![image](https://github.com/user-attachments/assets/8df0023e-4673-489d-b89d-485f8e8882ba)

**Comment by cuavas** [comment] 2024-07-23 20:11
Did something change with the SCSI controller between those releases?

@svenschnelle if you’re around, do you see anything suspicious between MAME 0.254 and 0.255 that would affect those machines?

**Comment by svenschnelle** [comment] 2024-07-23 20:34
Yes, i noticed that as well, but didn't have time to fix it. It's likely caused by 4ce29b652e8 ("mb87030: Make DMA transfers go through DREG rather than separate single buffer"). With this commit, DMA is served via the FIFO in the MB87030, but handshaking is broken. Simply reverting the commit as a quick fix works for me.

**Comment by ajrhacker** [comment] 2024-07-24 19:51
I still insist that the old MB87030 behavior was incorrect, and that the fault lies more in the emulation of the HP98620 DMA Controller. I have never seen any documentation for HP98620, but I can tell that its emulation of DMA transfers is very far from how any actual hardware would perform them.

**Comment by svenschnelle** [comment] 2024-07-25 08:05
I didn't want to say your commit is wrong, actually i think the change to route DMA via FIFO matches what the hardware is doing  - it's just that mb87030 stops working with this commit.

I looked into this two months ago, and i noted two problems:

- HP98620 DMA only recognizes changes in DMAREQ, so HP98620 stops after transferring the first byte, because it doesn't see a change on DMAREQ (it still asserted because fifo still has data/can store data)
- MB87030 doesn't do the handshaking whether the FIFO is full/empty correctly. I don't remember the details, but the state machine would need an additional 'FIFO is full/empty, waiting for DMA' state to hold off the SCSI bus.
I'm not sure how you would implement the 'transfer rate' thing - calling the dma routines via timer? If you have a good example of how to implement a DMA controller in MAME let me know.

**Comment by rb6502** [comment] 2024-07-25 12:04
Is the 98620 documented as having DMAREQ edge-triggered instead of level-triggered?  That would be somewhat unusual in my experience, but if it's true that points to the MB87030 needing to briefly dessert DMAREQ each time it updates the state, regardless of it the next state is asserted or cleared.

MB87030 absolutely should update DMAREQ based on the FIFO.  The FIFO state itself reflects handshaking with the SCSI bus.  This is how most common SCSI controllers work (e.g the 5380 and 539x).

**Comment by svenschnelle** [comment] 2024-07-25 12:49
For anyone interested, DMA Operation is described in http://ftp.bitsavers.org/pdf/hp/9000_dio/98562-90010_DIO_II_Accessory_Development_Guide_Feb87.pdf, Chapter 8.

**Comment by rb6502** [comment] 2024-07-25 23:49
Ok.

"Note 1: The I/O card may keep DMAR low after its request is acknowledged if it intends to do multiple DMA cycles."

and

"Note 2: To request another DMA cycle, the I/O card must assert DMAR within the specified time after the memory device's DTACK. After satisfying this requirement (Specification 2 in Table 8-2), the HP 98625A disc interface card can set DMAR high. Thus, during the next cycle, DMAR may still be high when DMACK goes low."

So what I get from those two is that DMAR is level triggered, not edge triggered, and it's totally valid to just hold DMAR for multiple cycles.  But if you *want* to briefly de-assert it and still do multiple cycles, you have to re-assert it in the specified window after DTACK.

 The MB87030 is fine, the 98620 just needs to keep performing transfers as long as DMAR is asserted.

**Comment by rb6502** [comment] 2024-07-25 23:54
Note: the inversion bars got lost when I copied out of the PDF, but DMAR is /DMAR, active low, hence note 1 saying to "keep /DMAR low".

**Comment by svenschnelle** [comment] 2024-07-26 05:22
That's not what i meant - i meant that the current implementation of the HP98620A in MAME only recognizes changes, not that the real hardware is edge triggered, which is wrong.

**Closed** 2024-07-26 12:05 UTC
