### ISSUE TITLE
LUA ERROR - plugins/cheat/cheat_xml.lua - every time i play a roms whit cheat xml files....

### ISSUE THREAD

**Issue by DjDiabolik** [mamedev/mame#6114] opened 2019-12-31 15:51 UTC
.... appears this errors and say:
LUA ERROR in execute function... etc etc etc..... cheat_xml.lua:79 attempt to index a nil value (field '?').
Press OK and i can play the games but not at fullscreen.

How i can fix this issue ?

If really need i can post a screenshot of this errors when try to run a games..... thanks in advance.

**Comment by Tafoid** [comment] 2019-12-31 15:57
Such .lua problems come about where you are using older versions of core files than provided with newer binaries.  Are you positive that your binary and core files required match?  Are you in Windows or another OS?

**Comment by DjDiabolik** [comment] 2019-12-31 17:38
Oh... sorry for bad information.
I'm on windows build... i have download the mameui from, i thinks, official mirror here:
http://mameui.info/

And i have extracted over my previous version how i ever do.......

I have already tryed to delete all both folder "cheat" and "cheatfind" and reput all files picked from here github but apparently i can fix this little trouble.
I have also open a thread on mamecheat.co.uk forum to obtain some information... i have put also a screenshot of errors.. you can found here:
https://i.imgur.com/xw0415s.png?1

**Comment by Tafoid** [comment] 2019-12-31 19:00
The problem is that you are not using an official binary release from https://www.mamedev.org   We only support these integer releases from that site and not other variants which have additional code and may/may not include proper support files.

The only suggestion I can offer is that you attempt a clean install of your MAMEUI package in a new folder and not overwriting your previous install and see how that works as I'm fairly sure something from previous versions would be causing your issue.  I cannot duplicate it with a freshly installed version.

If you continue to have issues with a freshly installed MAMEUI, post at their forum for help.
https://www.mameworld.info/ubbthreads/postlist.php?Cat=&Board=mameui

Closing

**Comment by cracyc** [comment] 2019-12-31 19:38
> And this errros it's appears only if i try to run a roms whit a xml cheat files

Which one?

**Comment by DjDiabolik** [comment] 2020-01-04 10:23
@cracyc for example a games.... right now i have test whit "spdodgeb.zip" and his cheat xml.
The xml it's write by me.... it's:
`<?xml version="1.0"?>

<mamecheat version="1">
	<cheat desc="Secondi Infiniti">
		<script state="run">
			<action>:maincpu.ppb@078A=59</action>
		</script>
	</cheat>		
	<cheat desc="PL1 Gigante Immortale">
		<script state="run">
			<action>:maincpu.ppb@04CD=10</action>
		</script>		
	</cheat>
	<cheat desc="PL1 Gigante Quasi Morto">
		<script state="on">
			<action>:maincpu.ppb@04CD=01</action>
		</script>		
	</cheat>	
	<cheat desc="PL1 Normale 3 (Basso a Destra) Immortale">
		<script state="run">
			<action>:maincpu.ppb@045D=10</action>
		</script>		
	</cheat>	
	<cheat desc="PL1 Normale 3 (Basso a Destra) Quasi Morto">
		<script state="on">
			<action>:maincpu.ppb@045D=01</action>
		</script>		
	</cheat>	
	<cheat desc="PL1 Normale 1 (Alto a Sinistra) Immortale">
		<script state="run">
			<action>:maincpu.ppb@0495=10</action>
		</script>		
	</cheat>
	<cheat desc="PL1 Normale 1 (Alto a Sinistra) Quasi Morto">
		<script state="on">
			<action>:maincpu.ppb@0495=01</action>
		</script>		
	</cheat>	
	<cheat desc="PL1 Normale 2 (Alto a Destra) Immortale">
		<script state="run">
			<action>:maincpu.ppb@0425=10</action>
		</script>		
	</cheat>	
	<cheat desc="PL1 Normale 2 (Alto a Destra) Quasi Morto">
		<script state="on">
			<action>:maincpu.ppb@0425=01</action>
		</script>		
	</cheat>	
</mamecheat>`

When i lauch this games it's errors appears.

@Tafoid great suggestion... i can also tryed a new clean "installation" but i need some question.
For some games i have some saved progresssion... NBA Turnament edition i have a player name whit password whit a score saved are you know how it's works ? If i do a clean install i lost everythings.... how i need to backup to my current setup ?? the "nvram" folder ??

**Comment by MooglyGuy** [comment] 2020-01-04 11:13
I can at least confirm that the XML you have provided is valid XML.

However, without trying to be insulting, I must admit that your English is difficult to understand. Do you have any friends who can better translate what it is you want to say from Italian to English? It is difficult to help a person that we cannot understand.

**Comment by DjDiabolik** [comment] 2020-01-04 11:17
@MooglyGuy lol i know i have a bad english :)

otherwise look my xml......  try to load my xml on cheat plugins and you can obtain my same errors.
You need to modify to be load correctly.

**Comment by MooglyGuy** [comment] 2020-01-04 11:22
No problem, I just wanted to clarify that the language barrier makes things difficult. :)

I will try your cheat XML and see if it also has an error. Just to confirm, is it "spdodgeb" that you are using this XML with?

**Comment by DjDiabolik** [comment] 2020-01-04 11:24
@MooglyGuy yes... spdodgeb.xml.
If you want i can attach my xml like on openload or other host site.

**Comment by MooglyGuy** [comment] 2020-01-04 11:49
Again, we do not support derivative builds like MAMEUI here.

I can confirm that your cheat XML works perfectly, without errors, on the latest official command-line version of MAME. See the attached screenshot.

I took your spdodgeb.xml, packaged it into a file called cheat.zip, put it in the same directory as the MAME executable, enabled the "cheat" option in mame.ini, and it works without issues.

If you continue to have issues with cheats and MAMEUI, please take it up with the author of MAMEUI, because this is not the appropriate place to do so.
![Uploading spdodgeb.png…]()

**Comment by DjDiabolik** [comment] 2020-01-04 11:54
mmmmmmm....... strange. i will try to ask on mameui official parts on forums if needed.

**Comment by MooglyGuy** [comment] 2020-01-04 12:04
Hi DJ,

Even though we do not officially support MAMEUI, I figured I would check MAMEUI just in case. I have also confirmed that your spdodgeb.xml works fine with the latest version of MAMEUI64 (0.217).

- I extracted the MAMEUI64 archive into its own directory. 
- I then placed the ZIPped ROM set for spdodgeb in the "Roms" directory.
- I then placed a file, "cheat.zip", containing your spdodgeb.xml, in the same directory as MAMEUI64.exe.
- I then edited the properties for Super Dodge Ball (US), and enabled cheats in the Debug tab, as shown in the attached screenshot:

![image](https://user-images.githubusercontent.com/1891617/71765251-836acf80-2ef2-11ea-94b7-04f87180adb6.png)

- I then started the game, pressed Tab, went to the "Cheats" option, and observed that your cheat XML is working correctly. It looks the same as the previous screenshot that I attached, but it is running via MAMEUI64 this time.

![image](https://user-images.githubusercontent.com/1891617/71765276-b6ad5e80-2ef2-11ea-8277-c94eba71b64e.png)

Please follow the steps above, and let me know if they work for you. Thanks!

**Comment by DjDiabolik** [comment] 2020-01-04 12:19
@MooglyGuy but have you tryed the cheat lua plugins ? The issue it's releated to this LUA plugin....
Apparently the cheat lua plugin can't load correctly the xml if contain the ":" before maincpu.....

**Comment by MooglyGuy** [comment] 2020-01-04 12:28
Ah ha, thank you for the clarification! :)

I'm not sure how to use the cheat LUA plugins, but once I work it out I'll let you know what my results are.

**Comment by DjDiabolik** [comment] 2020-01-04 12:31
@MooglyGuy for load the lua plugins you need to create a plugin.ini inside the "INI" folder.... somethigs like this:
```
#
# PLUGINS OPTIONS
#
cheat                     1
cheatfind                 1
console                   0
data                      1
dummy                     0
hiscore                   0
layout                    0
timer                     0
```
At this point the "cheat" and "cheatfind" plugins as been loaded when you launch a games.
At this point i thinks you also obtain the errros.
Apparently the currently mameui 0.217 need to create this plugin.ini file manually...... problably a bug.

**Comment by MooglyGuy** [comment] 2020-01-04 12:40
@DjDiabolik I can confirm that this is a valid bug, both with MAMEUI and standard MAME.

MAMEUI pops open a modal dialog to show the message, but standard MAME still prints this error message to the console.

@cracyc Is this something that you can look into?

**Comment by MooglyGuy** [comment] 2020-01-04 13:07
@DjDiabolik Please grab the latest version of cheat_xml.lua from here: https://github.com/mamedev/mame/blob/master/plugins/cheat/cheat_xml.lua

Replace the existing version in your directory with the new version, and please let me know if it works for you.

**Comment by DjDiabolik** [comment] 2020-01-04 13:43
@MooglyGuy i have already tryed this.... apparently i have already the same .lua files because i have compare (with notepad++ after i have open both files) my whit this and it's the same.

**Comment by MooglyGuy** [comment] 2020-01-04 14:35
You have downloaded the wrong file, because you can look at my commit here:

https://github.com/mamedev/mame/commit/7486fe3ce0ee6b449829646e22c8de166bb72df4

And see that it contains changes to the .lua file that I mentioned. Please try to download it again from the link that I provided, and then check the file compare.

**Comment by DjDiabolik** [comment] 2020-01-04 18:34
Ah... there's a recent commit :) I have tested this file about 5 or 6 days ago before to open this issue :)

Right now i have modified all my xml files and i have removed all ":" before maincpu strings...... i thinks i can tryed to restore a not modifield xml and test this "newest" cheat lua plugins.
Wait some feedback in some moments.

**Comment by DjDiabolik** [comment] 2020-01-04 19:56
@MooglyGuy it's apparently right now all it's working.... i have take a look at code (with my thin acquaintances) and i see now the ":" from the cpu line it's stripped out.. it's right ?

I have created this xml myself using the internal debugger cheatengine and when you save the xml cheat the ":" it's included.
I have look all other xml i have and infact all have the ":" in cpu line....... but on cheat.7z archive found online there's no strange character on cpu line....

**Comment by MooglyGuy** [comment] 2020-01-04 20:06
@DjDiabolik The purpose of the ":" is to specify that it is a 'root' device, and not a device owned by another device.

Consider a system that has an expansion slot: An expansion device might be named "my_exp", and any CPUs that belong to the expansion device could be named "cpu1", "cpu2", and so on. The full path to these CPUs would be ":my_exp:cpu1" and ":my_exp:cpu2".

Knowing this, I'm unsure of how correct my fix is. It effectively makes any root device references into relative device references instead. But since cheats should be using fully-qualified device paths anyway, I don't think it's that much of an issue.

But again, I think maybe the correct fix would be to make the internal cheat engine strip off the ":" rather than make the cheat loader omit the ":".

In this case I will stick with my existing solution, since it works for you, but I will leave the issue open, as I would like @cracyc to investigate the issue more deeply and see if it can be fixed in a better way.

**Comment by DjDiabolik** [comment] 2020-01-04 20:30
@MooglyGuy otherwise i have already say... i have modified all my little xml cheat list using Notepad++.
I have removed all ":".... a famous Italian phrase says "HO TAGLIATO LA TESTA AL TORO" :)
Google Translator suggest "I cut the bull's head off" but problably it's bad traslation :)

**Comment by DjDiabolik** [comment] 2020-01-05 15:53
@MooglyGuy only for confirmation....... later last night i have tryed to found some cheat for a different games.
Also i ever do i used the internal dedugger cheat engine...... when you found some result it's possible to write the result on a xml files using the command:
cheatlist test.xml

For confirm it's this command write :maincpu.ppb in strings.......

**Comment by cracyc** [comment] 2020-01-22 15:14
>But since cheats should be using fully-qualified device paths anyway, I don't think it's that much of an issue.

Cheats have to use fully-qualified device paths so this fix is fine.  Closing

**Closed by cracyc** 2020-01-22 15:14 UTC
