### ISSUE TITLE
Street Fighter II Hyper Fighting and clones running too fast

### ISSUE THREAD

**Issue by jmodlin210** [mamedev/mame#9005] opened 2021-12-17 02:41 UTC
Street Fighter II Hyper Fighting and clones are running too fast.

**Comment by 0kmg** [comment] 2021-12-17 02:53
If this is an issue with a release version of MAME, please report it at mametesters.org. Either way you'll need to provide a more detailed description of the problem and how to reproduce it. Exactly what is running to fast?

**Comment by angelosa** [comment] 2021-12-17 02:54
Duplicate of [MT#00408](https://mametesters.org/view.php?id=408) etc. etc. etc.

**Closed by angelosa** 2021-12-17 02:54 UTC
