### ISSUE TITLE
HLSL is still acting up even after updated bloom.fx and distortion.fx in current repo

### ISSUE THREAD

**Issue by old-gamer** [mamedev/mame#11003] opened 2023-03-19 16:25 UTC
### MAME version

0.252 (mame0252) nightly version

### System information

Windows 10 Home, 64-bit, version 22H2, USA, US English
Installed RAM 8.00 GB
AMD A6-5200 APU with Radeon(TM) HD Graphics 2.00 GHz
d3d video output

and another machine
Windows 10 Home, 64-bit, version 22H2, USA, US English
Installed RAM 4.00 GB
Intel(R) Pentium(R) CPU B950 @ 2.10GHz
d3d video output

### Incorrect behaviour

Similar to my previous issue here https://github.com/mamedev/mame/issues/10977
Bloom still looks weird
Phosphor decay just smears the screen

### Expected behaviour

Bloom should not look like odd blobs and phosphor decay should not smear the screen with default mame settings

### Steps to reproduce

1. start mame
2. enable d3d and hlsl
3. run any vector game, maybe any game in general

### Additional details

I can't really nail this down too much right now, but I tried latest mame nightly from here:
https://ashura.mameworld.info/nightlybuilds/builds.html
https://git.redump.net/mame/commit/?id=57dc2dc9a60ea4b1fbc6d1083c4f1ea7a805f2a2
https://www.mediafire.com/file/nddyukclm7ke7ky/16032023-13.44_mame.7z/file

claims to be official but I don't have a build environment for this emulator so will have to do.  Anyway this issue doesn't appear fixed as it was or something else is causing this, maybe all of the other fx files for hlsl need checking at this point although I'd assume that was done already when bloom.fx got updated after the distortion.fx?  I used the new bloom and distortion files and the other files from 0.252 since nightly only has the executable.

It also is doing different things in windowed and fullscreen similar to before.
Fullscreen default (smearing, maybe bad phophor decay rendering)
![0000](https://user-images.githubusercontent.com/127580438/226189525-ade8a665-1f1b-4919-a522-64d95f77d81c.png)

windowed default (bloom looks like blobs, light source isn't even where it should be)
![withnewfxfiles](https://user-images.githubusercontent.com/127580438/226189275-2ac7755b-0df7-4f73-9b07-08ae453b7c99.png)

videos comparison:
fullscreen (smearing)
[fullscreen0001.webm](https://user-images.githubusercontent.com/127580438/226189617-43e8bad0-0403-4b6c-b03b-0aff48e925ff.webm)

windowed (note it still shimmers like before the fix, still not correct!)
[window0000.webm](https://user-images.githubusercontent.com/127580438/226189673-6900bfd2-97ae-4768-a964-c7ace888a025.webm)

**Comment by old-gamer** [comment] 2023-03-19 16:31
Ugh, maybe this one can be closed.  Just saw the repo was updated by Ryan after I tried to type all this up.  Maybe I'll check again if the other site pushes out another updated exe.

**Comment by MooglyGuy** [comment] 2023-03-19 16:37
Yes, this should be closed. The pull request was merged just minutes ago, and you're testing against a nightly build, which would obviously not have the code changes associated with the pull request.

**Closed** 2023-03-19 16:37 UTC

**Comment by john-iv** [comment] 2023-03-19 19:37
@MooglyGuy The smearing appears to still happen with latest checkins as of 2 mins. ago and a clean build of 0.252 (mame0252-312-gf38ddbdc5f5)

If I run `mame asteroid -norc -hlsl` it works, but there is no brightly colored vectors.
If I run `mame asteroid -hlsl` with the attached freshly created mame.ini (via 'mame -cc') using the HLSL / artwork / vector.ini files from this morning, I get the smearing. DX9 installed.

Files used attached.

![asteroid](https://user-images.githubusercontent.com/9202235/226204610-fa191be3-d56d-4aa1-8c88-c2e498936333.png)
[SmearingFiles.zip](https://github.com/mamedev/mame/files/11012095/SmearingFiles.zip)

**Comment by MooglyGuy** [comment] 2023-03-19 19:46
I have no idea what "a clean build of 0.252 (mame0252-312-gf38ddbdc5f5)" even means.

Just pull the latest source code and compile it yourself, FFS.

**Comment by MooglyGuy** [comment] 2023-03-19 19:48
Also, if you're using HLSL files from this morning and not after this latest commit, yeah, that would be part of the problem. Stop it.

**Comment by MooglyGuy** [comment] 2023-03-19 19:56
![asteroid](https://user-images.githubusercontent.com/1891617/226205493-295142d1-0649-4b1f-b14b-b10dc23a87e9.png)

Here's what Asteroids looks like for me, with the mame.ini file you supplied, the vector.ini and vector-mono.ini files you supplied, all of the artwork files you supplied, and the .fx files that you supplied.

The only conclusion that I can come to is that whatever "mame0252-312-gf38ddbdc5f5" is, is not actually a build of the latest CODE. Because, you see, if CODE changes, then you need to COMPILE it. Stop wasting my time.

**Comment by john-iv** [comment] 2023-03-19 19:58
That's windowed Ryan, where it does work.  Try it fullscreen.
And it's a self compile using make clean then a full make producing the following version information 0.252 (mame0252-312-gf38ddbdc5f5)

**Comment by DavidHaywood** [comment] 2023-03-19 23:02
absolute latest code + resources here (self-compiled) gives the same results as John
https://i.postimg.cc/rsb771Nb/badast.png

**Comment by old-gamer** [comment] 2023-03-20 12:45
I'm going to follow up as well.  This I compiled overnight, took over 8 hours, checked just now.

0.252 (mame0252-316-ge1cd51fc9be)
fullscreen
![smearoids](https://user-images.githubusercontent.com/127580438/226342125-e91d7887-59da-4e73-adf4-170d9547ac3d.png)

windowed
![windowedlookscorrect](https://user-images.githubusercontent.com/127580438/226342241-df08c79a-d1eb-4853-8101-5e4b14b6ca0f.png)

So yes this is still a problem.

**Comment by john-iv** [comment] 2023-03-20 14:39
Asteroids fullscreen verbose launch.

[Asteroids Fullscreen Launch Verbose Output.zip](https://github.com/mamedev/mame/files/11019364/Asteroids.Fullscreen.Launch.Verbose.Output.zip)

**Comment by cuavas** [comment] 2023-03-20 20:42
52e150bcfd4128784bb73fb418ed076c99e887c1 should fix smeared vectors.

**Comment by john-iv** [comment] 2023-03-20 20:59
Confirmed as fixed on my system, thank you.

**Comment by john-iv** [comment] 2023-03-20 23:12
Does anyone else @DavidHaywood @cuavas see a bloom difference in Windowed / Fullscreen mode w/ this code change in place?  On my system the windowed version is 'bloom-ier' and looks more like the prior behaviour before the last HLSL reworking.  Attached images, windowed / fullscreen.  Radeon 5600XT, Win11.

![windowed](https://user-images.githubusercontent.com/9202235/226485063-3a18d4c4-ba8e-4c5f-86f5-fb22bcf09f3e.png)
![fullscreen](https://user-images.githubusercontent.com/9202235/226485065-d71a2bab-2148-42d7-b3ea-8040922e74fb.png)

**Comment by old-gamer** [comment] 2023-03-21 00:01
I could but I wouldn't know until tomorrow as compiling takes a full 8 hour shift on the AMD quad core.  Looks like the beam-width or intensity is different in your screenshots though.

**Comment by john-iv** [comment] 2023-03-21 00:05
It looks like even in your existing screen compares that your full and windowed versions did have different appearances besides the smearing.  So the bloom / beam width / intensity difference is probably not a regression w/ this one line fix.

**Comment by old-gamer** [comment] 2023-03-21 00:07
I disabled the vector presets, I only use the main mame.ini when testing.  It has all the settings anyway.

**Comment by john-iv** [comment] 2023-03-21 00:11
@cuavas @MooglyGuy I can peel this off into a new issue if you think it's too far afield from the original report.
