### ISSUE TITLE
Afterplugging Config Reset Bug

### ISSUE THREAD

**Issue by shinra358** [mamedev/mame#1347] opened 2016-08-30 01:29 UTC
Related to this issue:
https://github.com/mamedev/mame/issues/1248

Whenever you turn on your controller after the emu starts, you configuration gets reset and you would have to do all your button configs all over again. If you turn on the gamepad after the emu has started and you pressed esc on the mame menu to close it, you sometimes get an error message.

**Comment by rb6502** [comment] 2016-09-08 20:37
This is a duplicate of #1107 (https://github.com/mamedev/mame/issues/1107).

**Closed by rb6502** 2016-09-08 20:37 UTC

**Comment by tallpr24** [comment] 2017-06-15 12:23
Hey guys,
new to mame here.
I'm using mame0.816ui. My Xbox 360 controller wireless keeps losing the config in Mame.  I thought it was happening when I launched mame without my controller turned on but tried it again today and lost the config again even though the controller was on.  I changed the config file to be read only, not sure what else to do.  any suggestions.  I have mame and roms in the root of c drive.
