### ISSUE TITLE
Controller mappings are erased when the controllers don't exist

### ISSUE THREAD

**Issue by Catarax** [mamedev/mame#1107] opened 2016-07-16 13:53 UTC
If I configure a game with 360 controls, they will be automatically reset to keyboard if I start the game over again without my controller plugged.
Same thing for second 360 controller.

**Comment by Tafoid** [comment] 2016-07-16 16:43
The current solution we've been suggesting is, once you have your global (default) configuration correct with your pad mapped, adjust the file properties of the .CFG file to READ ONLY so it does not get overwritten when you exit MAME without the controller plugged in.  This should retain the mappings for you the next time you load MAME.

**Comment by angelosa** [comment] 2016-07-16 20:01
imho a design flaw tho: if you set a button with a xbox 360 / one controller, by unplugging the given pad then trying to run MAME it first gives "n/a" in the global settings then resets to default automatically when emulator is closed for whatever reason.

**Comment by Catarax** [comment] 2016-07-17 17:10
Yes Read-only is the only good tip but it will definitively lock the possibilty to use the panel.
The JOY keys should not become N/A if the pad is unplugged after next boot.

**Comment by bradhugh** [comment] 2016-07-17 20:59
I was under the impression this was a problem with all controllers / gamepads. Is this a problem exclusive to Xbox controllers?

**Comment by Catarax** [comment] 2016-07-17 22:24
Can't say much more, but probably because if they are also labelled as JOY.

**Comment by rb6502** [comment] 2016-07-18 01:31
This feature exists because long ago people would configure MAME to be controlled exclusively with joypads, and then be unable to operate MAME when one went bad or got unplugged.  Removing the mappings for joypads that don't exist guarantees you have some form of control restored to the user.

It's not a problem, it's fully intentional.

**Comment by Catarax** [comment] 2016-07-18 12:54
For wireless controller this is a huge problem because they aren't always connected to PC and they absolutely have to be connected before Mame is launched, else nothing is recognized.

**Comment by angelosa** [comment] 2016-07-23 15:40
Arbee, happens with laptops, you don't have the need to have a joypad attached all the time. 
imho it just feels to be an option declared in mame.ini

**Comment by anewuser** [comment] 2017-05-15 03:15
I know that the above posters have already replied to @rb6502, but I'd like to point out that the first part of his comment is also invalid. This happens even when you set _both_ keyboard and gamepad mappings for each button. The gamepad entries are erased the next time you use MAME with it not plugged in.

**Comment by tallpr24** [comment] 2017-06-15 12:22
Hey guys,
new to mame here.
I'm using mame0.816ui. My Xbox 360 controller wireless keeps losing the config in Mame.  I thought it was happening when I launched mame without my controller turned on but tried it again today and lost the config again even though the controller was on.  I changed the config file to be read only, not sure what else to do.  any suggestions.  I have mame and roms in the root of c drive.

**Comment by shinra358** [comment] 2017-06-15 16:06
It's obvious this is never going to be fixed. Just use retroarch to save yourself the trouble. I don't know why this is such a hard thing to do after it's already been done countless times in other emus and legit pc games alike, smh.

**Comment by tallpr24** [comment] 2017-06-15 16:29
i didnt know you can use retroarch for mame games.  does it work just as good?

----- Original Message -----

**Comment by stilett0** [comment] 2017-06-15 16:52
Hey guys, please go elsewhere to discuss MAME forks, we do not offer support for them.

**Comment by tallpr24** [comment] 2017-06-15 18:00
hi stilett0, im looking for support MAME controls. is this not the right place for this question??

**Comment by Catarax** [comment] 2017-06-15 18:01
Please stop, they will never fix that or add an option for it.

**Comment by tallpr24** [comment] 2017-06-15 18:07
understood, was looking for sort of work around.  I tried making the .cfg file read only but no go.

**Comment by tallpr24** [comment] 2017-06-15 18:11
Catarax, can you help with the making the file read only?

**Comment by happppp** [comment] 2017-06-15 18:56
Discussion related to this issue is fine. Just keep it on-topic.
tallpr24 please stop cross-posting your problem into other threads.

**Comment by rb6502** [comment] 2017-06-15 19:09
This is fixed with the new switch to specify controllers by GUID.  I am not a Windows user so I can't provide details, but I know it does work.

**Comment by tallpr24** [comment] 2017-06-15 21:22
Hmm, wonder if anyone else in this forum can chime in on your suggestion..
I going crazy trying to get this work.

**Comment by slydog43** [comment] 2017-08-03 18:07
By using GUID for each controller, I have overcome this trouble.  Check it out

**Comment by j8r** [comment] 2021-09-15 18:40
Reviving this old thread: one middle ground would be to have a toggle feature in the mame configuration to at least disable this default behavior.
Using IDs is not great, because one (like me) can have several controllers which will otherwise work out-of-the-box.

**Comment by j8r** [comment] 2022-09-11 15:38
I can no longer reproduce the reset of the "invalid" controller configurations on recent versions of MAME, unplugging any controller - including my mouse to be sure, doesn't change anything in `~/.mame/cfg/default.cfg`, which has the `-rw-r--r--` permissions.

**Comment by cuavas** [comment] 2022-09-15 07:03
Ah right, this is fixed by dd43f801a1839b526de1f3b0196d27073c0ebd7a.

**Closed by cuavas** 2022-09-15 07:03 UTC
